### ISSUE TITLE
[BUG] Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#114]
**Describe the bug**
In Area component
A Warning message: Each child in a list should have a unique "key" prop.

**To Reproduce**
1. Start project in development mode 'npm run dev'
2. Go to homepage
3. Open the developer console

**Expected behavior**
The warning message should be gone

**Screenshots**
![Screenshot from 2022-10-17 07-59-17](https://user-images.githubusercontent.com/6950941/196068439-42f22b92-cfa8-468d-8c92-309f5c919791.png)

**Comment by ugbeadie** [comment]
Hello @treoden, I tried running the 'npm run dev' and some other build commands but it isn't starting the project. However, this error can be fixed by simply passing a unique key(can be an id) as a prop to the component you are looping through(in your case, the Area component).

**Comment by treoden** [comment]
Hi @ugbeadie ,

You have to install the shop first, I suggest you try 
`npx create-evershop-app my-app --playAround`

_However, this error can be fixed by simply passing a unique key(can be an id)_ 
The thing is we need to have a same it between SSR and CSR. 

Thanks
