### ISSUE TITLE
[BUG] Failed prop type: Invalid prop `featuredProducts[0].productId` of type `string` supplied to `FeaturedProducts`, expected `number`.

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#116]
**Describe the bug**
Warning: Failed prop type: Invalid prop `featuredProducts[0].productId` of type `string` supplied to `FeaturedProducts`, expected `number`.

**To Reproduce**
1. Start project in development mode  'npm run dev'
2. Go to homepage
3. Check the developer console
5. See error

**Expected behavior**
The warning message should be gone

**Screenshots**
![Screenshot from 2022-10-17 08-04-48](https://user-images.githubusercontent.com/6950941/196068806-3f420b01-4e7e-4572-b383-e7f6b60cea45.png)

**Comment by mohitmohlia** [comment]
i'll take this issue

**Comment by nitin562** [comment]
I will try to solve this issue

**Comment by treoden** [comment]
Fixed.
