### ISSUE TITLE
[BUG] Failed prop type: Invalid prop `products[0].productId` of type `string` supplied to `ProductList`, expected `number`.

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#117]
**Describe the bug**
Warning: Failed prop type: Invalid prop `products[0].productId` of type `string` supplied to `ProductList`, expected `number`.

**To Reproduce**
1. Start project in development mode  'npm run dev'
2. Go to homepage
3. Check the developer console
5. See error

**Expected behavior**
The warning message should be gone

**Screenshots**
![Screenshot from 2022-10-17 08-06-42](https://user-images.githubusercontent.com/6950941/196068925-10b09f35-538e-498f-bb2f-aae5dd29f4b2.png)

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by treoden** [comment]
Sure @Vinitvh. Let me assign it to you
Thanks

**Comment by Vinitvh** [comment]
@treoden I have no error mentioning `Warning: Failed prop type: Invalid prop products[0].productId of type string supplied to ProductList, expected number.`

![evershop](https://user-images.githubusercontent.com/42197888/196370043-611f7fc2-e113-4a79-972f-e1cc88b979f1.png)

**Comment by evershopcommerce** [comment]
@Vinitvh ,

You must have at least 1 product on Homepage
Thanks

**Comment by Vinitvh** [comment]
Okay, got it. Should I have to manually insert a product?

**Comment by treoden** [comment]
Hi @Vinitvh ,

You can go to /admin and create a product. It will show up on the homepage,
Make sure the product is saleable (enabled, in stock ..etc)

**Comment by Vinitvh** [comment]
@treoden I can see `productId` is stored as an `INT` in database. But product coming from database has productId of type `string`?

**Comment by treoden** [comment]
Closing ticket. Thanks @Vinitvh
