### ISSUE TITLE
"Paid by customer" shows wrong value in order detail

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#142]

**Comment by LOGESH-B** [comment]
@treoden Can you tell me where it shows wrong
![image](https://github.com/evershopcommerce/evershop/assets/86541143/e80367c0-e1a7-4348-9006-fded33312ca2)

**Comment by treoden** [comment]
It shows wrong in order summary (grand total) from admin when user paid using Stripe
It does not effect the real amount paid by user, just the display issue

**Comment by mark-jia** [comment]
Weired paidAmount = transaction.amount.text displays 100 x correct amount
I need to work out the flow

**Comment by mark-jia** [comment]
Hi treoden, do you have access to the postgres database on the demo site?  I was wondering if the payment_transaction has the correct data for order # 13353 and #13354? Maybe it is not a display problem. When I look through the orders, some got correct display, some not, but they all use stripe payment.

**Comment by evershopcommerce** [comment]
It is due to the way Stripe handles the money amount. It does not use decimal, instead it use integer. We need to devide the value by 100 before saving the transaction amount to our db

**Comment by mark-jia** [comment]
I noticed that, how do you explain that #13350 has the correct number on the demo site?

**Comment by mark-jia** [comment]
I noticed Stripe has 3 category and 1 special.  
3 category currency: normal, zero decimal, 3 decimal currency
and there is a special

**Comment by mark-jia** [comment]
I think I am not going to take into account of 3 decimal currency, I will assume it is a zero decimal for simplicity and just do a division by 100 as a fix, do you agree?

**Comment by mark-jia** [comment]
what's your policy about testing, do you need to write a test script or you can pass if a very small changes?
