### ISSUE TITLE
CMS Pages not working

### ISSUE THREAD

**Issue by PinOnline** [evershopcommerce/evershop#162]
Test Link: https://demo.evershop.io/page/about-use

<img width="1144" alt="1" src="https://user-images.githubusercontent.com/88105090/209433756-9e210b4d-a4a4-4c21-8040-dc2a01fb0587.png">
<img width="1885" alt="2" src="https://user-images.githubusercontent.com/88105090/209433758-db61f455-4956-4370-bd6c-e8c975896bde.png">

**Comment by treoden** [comment]
Thanks @PinOnline . I will check
