### ISSUE TITLE
Emailing (SendGrid)

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#171]
This module takes care of email transaction
+ Order confirmation
+ Customer registration
+ Order update

Consider using SendGrid for email service

**Comment by kailash360** [comment]
@treoden 
Cam I work on this?

**Comment by treoden** [comment]
Sure @kailash360 ,

I want to design a kind of event based emailing. 
For example, when an order is placed an event will be created and we can subscribe to that event for email sending.
For now EverShop does not have event/subscribe yet.

Feel free to raise your idea. Thanks @kailash360
