### ISSUE TITLE
[FEATURE REQUEST] Code base should adhere to linting rules

### ISSUE THREAD

**Issue by 1two3code** [evershopcommerce/evershop#180]
**Is your feature request related to a problem? Please describe.**
The eslint config has not been followed 

**Describe the solution you'd like**
- [x] Run `npx eslint packages/evershop/src --fix` to fix the minor errors
- [x] Go through the rest of the source files and fix the remaining errors manually
- [ ] Add an eslint check to the github actions workflow to enforce adherence to the linting rules

**Describe alternatives you've considered**
- [ ] Add .eslintignore file with "**/*.js" and do it later 😢

**Additional context**
None

**Comment by treoden** [comment]
Thanks @1two3code ,

For now we will run auto fix and see how much it can do and continue for the rest.
We also need to setup a check to make sure this will not happen again. (Using lintstage or husky ideally )

Thanks

**Comment by treoden** [comment]
Dear @1two3code ,

So far I finished 2 of them. I also added and fixed prettier issues.

Can I ask for your support for the third item "Add an eslint check to the github actions workflow to enforce adherence to the linting rules" ?

Thank you

**Comment by 1two3code** [comment]
@treoden

It's great to hear you fixed the linting issues!
It'll make the contributing experience much more pleaseurable.

However, I will not be able to assist you with the github actions for a good while.
I got my hands full with other projects unfortunately.

I'm converting that task to an issue and close this issue.
