### ISSUE TITLE
[BUG] Attribute filter by name does not work properly

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#198]
**Describe the bug**
In admin, attribute grid page. The attribute name filter does not work properly

**To Reproduce**
1. Go to admin
2. Click on 'Attributes'
3. Input attribute name and hit enter

**Actual behavior**
It requires the input must be exactly a full name of attribute in order to find ones

**Expected behavior**
It should support "Like" query. User can just input part of a name and can file the attribute

**Comment by Abhishek7Tech** [comment]
@treoden Hi I would like to contribute!

**Comment by Abhishek7Tech** [comment]
@evershopcommerce Hi need some help with this. Something wrong with mySQL database.


WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:C:\Users\abhis\Documents\Open Source\evershop\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Error: Configuration property "system.database.host" is not defined
    at Config.get (C:\Users\abhis\Documents\Open Source\evershop\node_modules\config\lib\config.js:182:11)
    at Object.<anonymous> (C:\Users\abhis\Documents\Open Source\evershop\packages\evershop\src\lib\mysql\connection.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\abhis\Documents\Open Source\evershop\packages\evershop\bin\lib\bootstrap\migrate.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

**Comment by evershopcommerce** [comment]
You have to run “npm setup” to finish the installation. ( you need to have mysql db)

**Comment by Abhishek7Tech** [comment]
@evershopcommerce Looks like I need to install mysql db first. Any reference with mysql db

**Comment by evershopcommerce** [comment]
can you join the Discord channel. I will support

**Comment by Abhishek7Tech** [comment]
@evershopcommerce ok I will

**Comment by Abhishek7Tech** [comment]
I am getting this error now.
![Screenshot (55)](https://user-images.githubusercontent.com/93655183/218259298-2fe07533-4f11-4906-af1c-00c83b30481c.png)

**Comment by evershopcommerce** [comment]
Are you sure “root” does not have password?

**Comment by Abhishek7Tech** [comment]
@evershopcommerce Hi figured it out! Thanks for the help.

**Comment by Abhishek7Tech** [comment]
@treoden Hi Check this filter out.
Input = "ava"
all the attributes with an "ava" will be rendered.

https://user-images.githubusercontent.com/93655183/218410375-2ea4e3cb-6c62-45aa-8de0-1bd98d1ea265.mp4

**Comment by treoden** [comment]
Hi @Abhishek7Tech ,

Thanks, give me sometime to review it.

**Comment by Abhishek7Tech** [comment]
Hi @treoden 

Ok !

**Comment by Abhishek7Tech** [comment]
@treoden @evershopcommerce Still waiting for the review feedback!

**Comment by treoden** [comment]
@Abhishek7Tech ,

You are doing the filter on client side. Which is not correct. The list of attribute could be longer (paginated)
We need to do the filter at the server level. I suggest you to check this file
https://github.com/evershopcommerce/evershop/blob/main/packages/evershop/src/modules/catalog/graphql/types/Attribute/Attribute.resolvers.js

Thanks

**Comment by Abhishek7Tech** [comment]
@Abhishek7Tech Ok I will try again.

**Comment by treoden** [comment]
Hi @Abhishek7Tech ,

The file I gave you is the resolver for attribute query. The idea is when user filter, the filters will be passed to the "attributes" function (line 19). We need to check the way we apply this filter to the database query (line 37 to 49)

Thanks

**Comment by Abhishek7Tech** [comment]
@treoden 
 
if (nameFilter) {
        query.andWhere(
          'attribute.`attribute_name`',
          nameFilter.operation,
          nameFilter.value
        );

it's clear we are asking in the query where attribute= attribute_name?

**Comment by treoden** [comment]
Hi @Abhishek7Tech ,

That is the code we need to fix:
I suggest to change it to:

```
// Name filter
      const nameFilter = filters.find((f) => f.key === 'name');
      if (nameFilter) {
        query.andWhere(
          'attribute.`attribute_name`',
          'LIKE',
          `%${nameFilter.value}%`
        );
        currentFilters.push({
          key: 'name',
          operation: '=',
          value: nameFilter.value
        });
      }
```

Thanks

**Comment by treoden** [comment]
Fixed. V1.0.0-rc1
