### ISSUE TITLE
[BUG] Bestseller product url lead to 404 page

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#199]
**Describe the bug**
When user click on a link from the best sellers product in Dashboard, it takes user to 404 page

**To Reproduce**
1. Go to admin dashbooard
2. Click on the link in Best sellers 
3. See 404 error

**Actual behavior**
It takes user to 404 page

**Expected behavior**
It should take user to the corresponding product editing page

**Comment by mohitmohlia** [comment]
Hi @treoden please assign this to me.

**Comment by treoden** [comment]
Hi @mohitmohlia , I fixed this issue already. Waiting for a release to close 

Thanks
