### ISSUE TITLE
[BUG] Customer link in order detail page shows 404 page

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#200]
**Describe the bug**
When user click on a link from the best sellers product in Dashboard, it takes user to 404 page

**To Reproduce**
1. Go to admin dashbooard
2. Click Orders menu and open an order 
3. Click on the customer name from the right side (Order placed by a logged in customer)
4. See 404 page

**Actual behavior**
It takes user to 404 page

**Expected behavior**
It should take user to the corresponding customer editing page

**Comment by mohitmohlia** [comment]
Hi @treoden please assign this to me

**Comment by mohitmohlia** [comment]
@treoden i am facing this problem while setting up the project
<img width="581" alt="Screenshot 2023-02-12 at 8 44 46 PM" src="https://user-images.githubusercontent.com/46368810/218319552-405fafda-01cd-4f13-87a2-875371bce72b.png">

**Comment by evershopcommerce** [comment]
Did you created a database named “evershop”? Ì not please created one. Installation only setup schema

**Comment by treoden** [comment]
Fixed. V1.0.0-rc1
