### ISSUE TITLE
[BUG] inside product details page product description in not showing

### ISSUE THREAD

**Issue by apexano** [evershopcommerce/evershop#206]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Background (please complete the following information):**
 - NodeJS Version
 - MySQL Version
 - EverShop Version
 - OS: [e.g. Window, Ubuntu, Mac-OS]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by treoden** [comment]
Closing as fixed in v.1.0.0-rc.1. Please upgrade your evershop
https://evershop.io/docs/development/getting-started/installation-guide#update-evershop
