### ISSUE TITLE
[FEATURE REQUEST] SSL/TLS support to database connection

### ISSUE THREAD

**Issue by Muntasir2001** [evershopcommerce/evershop#210]
**Is your feature request related to a problem? Please describe.**
Evershop does not support SSL/TSL connection to database (MySQL)

**Describe the solution you'd like**
An ideal solution would be setting up a way for Evershop to connect to the MySQL DB using SSL/TSL connection

**Describe alternatives you've considered**
Can't think of any alternatives. The current alternative which has been already implemented is the basic password auth which is not secure.

**Additional context**
Planetscale - serverless MySQL DB requires the client (eg: Evershop) to connect using SSL/TLS so it would be good to have that feature in Evershop.

**Comment by treoden** [comment]
Hi @Muntasir2001 ,

EverShop make uses of the mysql package (https://www.npmjs.com/package/mysql). This package is not actively maintenance and seems does not support ssl/tls connection.
I suggest to take a look the `mysql2` package. It looks so promising.

Thanks

**Comment by Muntasir2001** [comment]
@treoden cool I will have a look
Thanks

**Comment by treoden** [comment]
Closing as completed
