### ISSUE TITLE
[FEATURE REQUEST] Dockerize the app and translation guide

### ISSUE THREAD

**Issue by gmdig** [evershopcommerce/evershop#213]
Could you please dockerize the app to simplify the deployment?
btw, I need an instruction on how to use/add translation

**Comment by treoden** [comment]
Hi @gmdig ,

This is the translation guide: https://evershop.io/docs/development/knowledge-base/translation
This feature is only available from v.1.0.0.rc.1 which was released yesterday. So Please upgrade your evershop
https://evershop.io/docs/development/getting-started/installation-guide#update-evershop

Thanks
