### ISSUE TITLE
[FEATURE REQUEST] Facebook pixel events

### ISSUE THREAD

**Issue by cristian0791** [evershopcommerce/evershop#231]
**Is your feature request related to a problem? Please describe.**
Adding the facebook/instagram events tracking for better marketing purpose.

**Describe the solution you'd like**
Events: PageView, Add To Cart, Checkout Initiated, Purchase

**Comment by treoden** [comment]
This one should be cover by an extension. Not the core.
Thanks

**Comment by hfzi** [comment]
Hello, will facebook pixel and google analytics ecommerce support come when advertising? It is necessary to follow the events of the customers coming from the advertisement within the site. Thanks
