### ISSUE TITLE
[BUG] Currency not changing

### ISSUE THREAD

**Issue by coder-palak** [evershopcommerce/evershop#253]
**Describe the bug**
After changing the store currency we can still see the default USD dollar sign on product card price.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Background (please complete the following information):**
 - NodeJS Version
 - MySQL Version
 - EverShop Version
 - OS: [e.g. Window, Ubuntu, Mac-OS]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by treoden** [comment]
Fixed. Closing
