### ISSUE TITLE
[FEATURE REQUEST] Cloud storage for assets

### ISSUE THREAD

**Issue by coder-palak** [evershopcommerce/evershop#256]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by treoden** [comment]
Available from version 1.0.0-rc.9. We are now supporting Azure and AWS S3. Thanks

**Comment by gmdig** [comment]
> Available from version 1.0.0-rc.9. We are now supporting Azure and AWS S3. Please check here for the extensions: https://evershop.io/extensions
> 
> Thanks

Could you please make a mod for cloudflare r2?
