### ISSUE TITLE
Update Product UX

### ISSUE THREAD

**Issue by lzinga** [evershopcommerce/evershop#277]
**Is your feature request related to a problem? Please describe.**
Right now if you have one product which you would like variations for but slightly different you should be able to modify the price on a per-variation basis.

**Describe the solution you'd like**
For example if I have an item that comes with a keychain and another one that is exactly the same but without a keychain, you should be able to edit the variant to adjust the price. Within the variant section you can currently see the price but you are not able to edit the price.

**Describe alternatives you've considered**
Making a product listing for each option, however this would cause the product listing page to get cluttered with much of the same information.

**Comment by treoden** [comment]
Hi @lzinga ,

Actually you can edit the price per variant. For now you can click on the sku and go to the product detail editing. From here you can edit the price for that variant.  It will not affect to others variant

Thanks

**Comment by lzinga** [comment]
> Hi @lzinga ,
> 
> Actually you can edit the price per variant. For now you can click on the sku and go to the product detail editing. From here you can edit the price for that variant. It will not affect to others variant
> 
> Thanks

ah, I see it now. The process is slightly confusing to me. It may be only me but it may be worth it to change the UX here so things a little clearer.

Personally, I would expect the products admin page to have the product listings, if you wanted to show the variations it would be worth it to show them as a sub-list/table underneath their root product. Along with that it would allow you to possibly have an inline editor for the price, SKU, and quantity so you don't have to go inside the products to edit them.

Then from within the root product edit page you could have the link to the variation where you can add/edit details for the variant. When on the variant edit page too it could be beneficial to show the user they are editing a variant of a core product.

I mocked up a quick example. If I find the time and get more familiar with the project I might be able to work on something like this.
![image](https://github.com/evershopcommerce/evershop/assets/9082450/a76f7a28-0b71-4306-b0ca-e16be1ce0083)

**Comment by thgiang** [comment]
@treoden  Can you help me detect which once is variant product. I think there must be some difference in the database

**Comment by treoden** [comment]
Hi @thgiang ,

If you look to the product table you can check the column `variant_group_id` in the `product` table. From v1.1.0 you will be able to filter for the configurable product (has variant) from admin panel. Thanks
