### ISSUE TITLE
[FEATURE REQUEST] Nested pages and blog posts

### ISSUE THREAD

**Issue by MarkJDuwe** [evershopcommerce/evershop#285]
It would be nice to have nested pages so you could create parent - child pages for a more detailed shop structure as well as a blog section with categories and tags for posts.

**Comment by treoden** [comment]
Hi @MarkJDuwe ,

Static page should stay simple. And the blog, posts should be outside of the core. I suggest to make an extension for that feature
Thanks

**Comment by treoden** [comment]
Blog post available from 2.2.1
