### ISSUE TITLE
Attribute Groups issues

### ISSUE THREAD

**Issue by belousovgm** [evershopcommerce/evershop#288]
Hello folks!
It's really great project, I appreciate your effort!

I just noticed a bug related to attribute groups:

version: 1.0.0 rc-5
node: 18.16.0
OS: macOS 13.2.1 
postgres: 15

**pre-conditions:**
_you have at least one custom attribute_

**Steps to reproduce:**
1. Fill create product page (Do not select attribute, leave it "Default")
2. Tap "Save". Wait for page reloading
3. Tap "Create a variant group" and get error
4. Try to select another attribute group for product

**Expected:**
You're able to select another attribute group and create variant

**Actual:**
You always get error when trying to change attribute group.
Error message:
_You can not change the attribute group of a product that is already in a variant group._

There is no way to eliminate the error except delete and add product again.

-----------------

Another bug I noticed, you can add and buy item even if qty=0 in case product has several variants

**Comment by treoden** [comment]
Fixed in 1.0.0 rc-8. Thanks
