### ISSUE TITLE
[BUG] Error: Use process(css).then(cb) to work with async plugins at Object.TailwindLoader

### ISSUE THREAD

**Issue by MarkJDuwe** [evershopcommerce/evershop#295]
npm run build returns errors and the site does not load CSS or image files when running.

```
> evershop@1.0.0 build
> evershop build

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode

● Client █████████████████████████ sealing (92%)  

● Client █████████████████████████ sealing (92%) asset processing 
 Tailwindcss

● Server █████████████████████████ building (58%) 74/84 entries 5393/5394 dependencies 1328/1357 modules 29 active 
 node_modules/supports-color/index.js

● Client █████████████████████████ sealing (92%) asset processing 
 Tailwindcss

● Server █████████████████████████ building (58%) 74/84 entries 5393/5394 dependencies 1328/1357 modules 29 active 
 node_modules/supports-color/index.js

Error: Use process(css).then(cb) to work with async plugins
```

**Comment by treoden** [comment]
Hi @MarkJDuwe 
What is the version of @evershop/evershop you are using?

Thanks

**Comment by MarkJDuwe** [comment]
It's 1.0.0-rc.5

**Comment by eatmycookie** [comment]
Problem with latest tailwind version

**Comment by Khaleel** [comment]
Also having this issue

**Comment by Khaleel** [comment]
I think I found the fix - finally working for me so far.

Stop the application and run

```
yarn remove nativewind
yarn remove tailwindcss
yarn add postcss@8.4.23
yarn add --dev tailwindcss@3.3.2
yarn add nativewind
```
(if using npm use npm instead of yarn <3) Source: https://github.com/postcss/postcss/issues/412#issuecomment-1637120414

Then run `npm run build && npm run start` again - ensure all folders have been CHMOD 0777

Now it seems to be working

**Comment by estebanadams** [comment]
This one line of shell command fixed it for me `npm i --dev tailwindcss@3.3.2`

**Comment by berilslv** [comment]
Tried both fix's from @Khaleel and @estebanadams , still stuck at 92% 
Permisions are 0777 for folder too!
https://imgur.com/a/WtMNHz2

**Comment by estebanadams** [comment]
@berilslv Check in your package-lock or yarn.lock that you have the right version check also in your node module
Also don't forget to re build

**Comment by gtishenko** [comment]
Hello! I have same error, it's fixed by downgrade tailwindcss to 3.3.2.

After that error "Error: Use process(css).then(cb) to work with async plugins" is fixed, but now build stops at 87% and 58%, then process ends with message "killed". 
How can this be fixed?

<img width="557" alt="Screenshot 2023-07-27 at 17 37 55" src="https://github.com/evershopcommerce/evershop/assets/56306520/e91c93f2-e924-47d7-9abf-071d4e9c405c">

**Comment by treoden** [comment]
Hi @gtishenko ,

It is because of the Terser plugin. It takes times and resources.
Can you try `export NODE_OPTIONS="--max-old-space-size=8192" &&  npm run build`

Thanks

**Comment by gtishenko** [comment]
Nothing has changed... Same "Killed" message

**Comment by KavinCharlie** [comment]
Any improvements on this? I'm getting this same error.

**Comment by shu2k** [comment]
> This one line of shell command fixed it for me `npm i --dev tailwindcss@3.3.2`

Thanks! This fixed the issue for me.

**Comment by lebu7** [comment]
> I think I found the fix - finally working for me so far.
> 
> Stop the application and run
> 
> ```
> yarn remove nativewind
> yarn remove tailwindcss
> yarn add postcss@8.4.23
> yarn add --dev tailwindcss@3.3.2
> yarn add nativewind
> ```
> 
> (if using npm use npm instead of yarn <3) Source: [postcss/postcss#412 (comment)](https://github.com/postcss/postcss/issues/412#issuecomment-1637120414)
> 
> Then run `npm run build && npm run start` again - ensure all folders have been CHMOD 0777
> 
> Now it seems to be working



> I think I found the fix - finally working for me so far.
> 
> Stop the application and run
> 
> ```
> yarn remove nativewind
> yarn remove tailwindcss
> yarn add postcss@8.4.23
> yarn add --dev tailwindcss@3.3.2
> yarn add nativewind
> ```
> 
> (if using npm use npm instead of yarn <3) Source: [postcss/postcss#412 (comment)](https://github.com/postcss/postcss/issues/412#issuecomment-1637120414)
> 
> Then run `npm run build && npm run start` again - ensure all folders have been CHMOD 0777
> 
> Now it seems to be working

this one worked for me

**Comment by wintersakuraa** [comment]
> I think I found the fix - finally working for me so far.
> 
> Stop the application and run
> 
> ```
> yarn remove nativewind
> yarn remove tailwindcss
> yarn add postcss@8.4.23
> yarn add --dev tailwindcss@3.3.2
> yarn add nativewind
> ```
> 
> (if using npm use npm instead of yarn <3) Source: [postcss/postcss#412 (comment)](https://github.com/postcss/postcss/issues/412#issuecomment-1637120414)
> 
> Then run `npm run build && npm run start` again - ensure all folders have been CHMOD 0777
> 
> Now it seems to be working

When i run 
```
yarn remove nativewind
yarn remove tailwindcss
```
I get this
```
yarn remove v1.22.19
[1/2] 🗑  Removing module nativewind...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
```

**Comment by wintersakuraa** [comment]
Fixed by adding this to `package.json`:
```json
  "resolutions": {
    "tailwindcss": "3.3.2"
  }
```

**Comment by treoden** [comment]
Fixed.  Version 1.0.0-rc.7
