### ISSUE TITLE
HTML Lang Attribute Not Updated/Parsed

### ISSUE THREAD

**Issue by tszczypinski6** [evershopcommerce/evershop#297]
**Describe the bug**
When the language is set, HTML lang attribute is not updated/parsed, and therefore does not appear.

**To Reproduce**
1. Change Language in Config
2. Re-build
3. Continue to see standard html tag (`<html id="root">`)

**Expected behavior**
Expected HTML Tag: `<html lang="en" id="root">`

**Screenshots**

N/A

**Background (please complete the following information):**
 - NodeJS Version: 18.16.1
 - Postgres Version: 14.8
 - EverShop Version: 1.0.0-rc.5
 - OS: Ubuntu 22.04
 - Browser: Checked Firefox, Safari, Chrome

**Additional context**
Not sure if this is supposed to be updated automatically.

Required for SEO.

**Comment by treoden** [comment]
Fixed.  Version 1.0.0-rc.7
