### ISSUE TITLE
[BUG] Query root type must be provided

### ISSUE THREAD

**Issue by NamanGajjar26** [evershopcommerce/evershop#303]
In this project this error come and not show any data or home view in website install properly followed all steps on installation guide but error come "Query root type must be provided"

**Comment by evershopcommerce** [comment]
Can you show some code here @NamanGajjar26 ?

**Comment by treoden** [comment]
Hi @NamanGajjar26 ,

If this is a fresh installation without any customization, make sure you run "npm run build" before starting the app

**Comment by NamanGajjar26** [comment]
yes "npm run build" before starting the app

**Comment by NamanGajjar26** [comment]
not change any code download GitHub project and  extract zip and installed using your guide from your website

**Comment by treoden** [comment]
Can you share a screenshot of your terminal here @NamanGajjar26 ?

**Comment by NamanGajjar26** [comment]
![Capture2](https://github.com/evershopcommerce/evershop/assets/134602364/f751ff46-4681-4986-b13a-eec32f7bf619)

**Comment by NamanGajjar26** [comment]
any solution !

**Comment by treoden** [comment]
Humhhh. It is weird. Can you share a screenshot of your project folder? I want to see the folder named '.evershop' and '.evershop/build/frontStore/homepage'

Thanks

**Comment by NamanGajjar26** [comment]
this folder is not show

**Comment by treoden** [comment]
Maybe your computer does not show the hidden files. You can change the setting to show them @NamanGajjar26 https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5

**Comment by NamanGajjar26** [comment]
i am found

**Comment by NamanGajjar26** [comment]
![Capture3](https://github.com/evershopcommerce/evershop/assets/134602364/38f30bc4-0879-408e-9fd8-ebd0da78f3f4)

**Comment by treoden** [comment]
Can you show inside of the 'server' folder?

**Comment by NamanGajjar26** [comment]
![Capture3](https://github.com/evershopcommerce/evershop/assets/134602364/514a4703-474d-4770-8070-e76327c028b2)

**Comment by treoden** [comment]
It looks good. hummm. Can you just stop the app and start again?

**Comment by NamanGajjar26** [comment]
yes but nothing changes

**Comment by treoden** [comment]
Ok one more thing, Can you share the content of the 'query.graphql' file above here @NamanGajjar26 ?
Thanks

**Comment by NamanGajjar26** [comment]
{"query":"\n\n\n  ea0mnap8xolkjdfbrz: collection(code: \"homepage\") {\n    collectionId\n    name\n    products(filters: [{key: \"limit\", operation: \"=\", value: \"4\"}]) {\n      items {\n        productId\n        name\n        price {\n          regular {\n            value\n            text\n          }\n          special {\n            value\n            text\n          }\n        }\n        image {\n          alt\n          url: listing\n        }\n        url\n      }\n    }\n  }\n\n\n  ea0mnap8xolkjdfbs0: url(routeId: \"cart\")\n  ea0mnap8xolkjdfbs1: cart(id: \"getContextValue_ImNhcnRJZCIsIG51bGw=\") {\n    totalQty\n  }\n\n\n  ea0mnap8xolkjdfbs2: pageInfo {\n    breadcrumbs {\n      title\n      url\n    }\n  }\n\n\n\n\n  ea0mnap8xolkjdfbs3: menu {\n    items {\n      name\n      url\n    }\n  }\n\n\n  ea0mnap8xolkjdfbs4: pageInfo {\n    title\n    description\n  }\n\n\n  ea0mnap8xolkjdfbs5: menu {\n    items {\n      name\n      url\n    }\n  }\n\n\n\n\n  ea0mnap8xolkjdfbs6: customer(id: \"getContextValue_ImN1c3RvbWVySWQiLCBudWxs\") {\n    uuid\n    fullName\n    email\n  }\n  ea0mnap8xolkjdfbs7: url(routeId: \"account\")\n  ea0mnap8xolkjdfbs8: url(routeId: \"login\")\n","fragments":"\n\n\n\n\n\n\n\n\n\n\n\n","variables":"{\"values\":{},\"defs\":[]}","propsMap":{"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNhdGFsb2dccGFnZXNcZnJvbnRTdG9yZVxob21lcGFnZVxGZWF0dXJlZENhdGVnb3JpZXMuanN4":[],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNhdGFsb2dccGFnZXNcZnJvbnRTdG9yZVxob21lcGFnZVxGZWF0dXJlZFByb2R1Y3RzLmpzeA==":[{"origin":"collection","alias":"ea0mnap8xolkjdfbrz"}],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNoZWNrb3V0XHBhZ2VzXGZyb250U3RvcmVcYWxsXE1pbmlDYXJ0LmpzeA==":[{"origin":"cartUrl","alias":"ea0mnap8xolkjdfbs0"},{"origin":"cart","alias":"ea0mnap8xolkjdfbs1"}],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGFsbFxCcmVhZGNydW1iLmpzeA==":[{"origin":"pageInfo","alias":"ea0mnap8xolkjdfbs2"}],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGFsbFxMYXlvdXQuanN4":[],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGFsbFxMb2dvLmpzeA==":[],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGFsbFxNZW51LmpzeA==":[{"origin":"menu","alias":"ea0mnap8xolkjdfbs3"}],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGFsbFxNZXRhLmpzeA==":[{"origin":"pageInfo","alias":"ea0mnap8xolkjdfbs4"}],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGFsbFxNb2JpbGVNZW51LmpzeA==":[{"origin":"menu","alias":"ea0mnap8xolkjdfbs5"}],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGFsbFxOb3RpZmljYXRpb24uanN4":[],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGNtc1xwYWdlc1xmcm9udFN0b3JlXGhvbWVwYWdlXE1haW5CYW5uZXIuanN4":[],"XHBhY2thZ2VzXGV2ZXJzaG9wXHNyY1xtb2R1bGVzXGN1c3RvbWVyXHBhZ2VzXGZyb250U3RvcmVcYWxsXFVzZXJJY29uLmpzeA==":[{"origin":"customer","alias":"ea0mnap8xolkjdfbs6"},{"origin":"accountUrl","alias":"ea0mnap8xolkjdfbs7"},{"origin":"loginUrl","alias":"ea0mnap8xolkjdfbs8"}]}}

**Comment by treoden** [comment]
It looks fine. Ok give me some time to dig deeper into this. In the mean time please share your specification like the node version, npm version and your operation system. it can be helpful 

Thanks you

**Comment by NamanGajjar26** [comment]
node version v20.3.1, npm version 9.6.7 and windows -10

**Comment by NamanGajjar26** [comment]
data base in product and all table in not add any data

**Comment by treoden** [comment]
hi @NamanGajjar26 ,

The root cause is your folder name contains whitespace ("Github React Project"). Please change this name, make sure no whitespace, no special chars

Thanks
