### ISSUE TITLE
[FEATURE REQUEST] Usable default theme

### ISSUE THREAD

**Issue by kaysond** [evershopcommerce/evershop#309]
I'd like to build and use the default evershop without any custom theme. I don't need anything special, just a plain store front. Right now the theme that ships with evershop (and the example) are too specific to be usable. The only change that I think is needed is to have a front page that shows, for example, categories that are set up in the backend instead of specific ones. 

Thanks!

**Comment by treoden** [comment]
For anyone looking for an example of theme. Please checkout: https://github.com/evershopcommerce/evetheme/

Thanks
