### ISSUE TITLE
[BUG] "Add products" Does not work from category page

### ISSUE THREAD

**Issue by kaysond** [evershopcommerce/evershop#319]
**Describe the bug**
Clicking the "Add products" in the category causes an error due to an http500 response to the graphql query

**To Reproduce**
1. Go to Categories
2. Click on a category
3. Click "Add products"

**Expected behavior**
Products should come up like they do in Collections

**Background (please complete the following information):**
 - NodeJS Version: 20.3.1
 - Postgres Version: 15.4
 - EverShop Version: 1.0.0-rc.5
 - OS: [e.g. Window, Ubuntu, Mac-OS]: Debian (Docker)
 - Browser [e.g. Chrome, Safari] Firefox

**Additional context**
Failing query:
```json
{"query":"query Query($query: String) {\n  products: searchProducts(query: $query) {\n    items {\n      productId\n      uuid\n      sku\n      categories {\n        categoryId\n        __typename\n      }\n      name\n      price {\n        regular {\n          text\n          __typename\n        }\n        __typename\n      }\n      image {\n        url: thumb\n        __typename\n      }\n      __typename\n    }\n    total\n    __typename\n  }\n}","operationName":"Query","variables":{"query":""}}
```

Weirdly, the Collections page sends the same query but it returns http 200... I don't see any errors in the console either.

**Comment by treoden** [comment]
Hi @kaysond,

Can you share the version of evershop you are using?

Thanks

**Comment by kaysond** [comment]
@treoden whoops sorry I totally missed that part of the template. Updated. It's a5d4f02b1

**Comment by treoden** [comment]
Thanks @kaysond ,

This error was fixed in the recent release. Please upgrade your evershop to 1.0.0-rc.7
`npm install @evershop/evershop@latest` and then `npm run build`

Thanks

**Comment by kaysond** [comment]
Thanks!
