### ISSUE TITLE
[BUG] Adding to Cart from PDP - Qty not updating properly

### ISSUE THREAD

**Issue by Jokara998** [evershopcommerce/evershop#323]
**Describe the bug**
When I open a PDP, select qty picker, insert value of 3 and click add to cart button, number of cart items is 1 and also success popup has a qty value of 1.

**To Reproduce**
1. Open PDP of any product
2. Insert value bigger than 1 in qty input
3. Click add to cart button
4. See popup qty value (not valid)
5. Close popup and see number of items in cart in header (not valid)

**Expected behavior**
Qty in popup should be the same as in qty picker input on PDP.
Qty in cart icon in header should update properly.

**Screenshots**

![Screenshot from 2023-08-28 23-41-09](https://github.com/evershopcommerce/evershop/assets/52428675/11ec6570-ed14-4c27-a469-1db630c41193)
![Screenshot from 2023-08-28 23-42-47](https://github.com/evershopcommerce/evershop/assets/52428675/85684951-59c6-4570-960b-bb1b44718650)

**Background (please complete the following information):**
 - NodeJS Version: 14.18.2
 - Postgres Version: 13
 - EverShop Version: 1.0.0-rc.7
 - OS: Ubuntu 20.04
 - Browser Chrome

**Comment by treoden** [comment]
Fixed in `1.0.0-rc.8`. Thanks
