### ISSUE TITLE
[FEATURE REQUEST] Product Tile - Add to Cart

### ISSUE THREAD

**Issue by Jokara998** [evershopcommerce/evershop#324]
**Is your feature request related to a problem? Please describe.**
E-commerce apps in many cases have an AddToCart button on ProductTile (on Featured Products, on Related Products, on PLP).

**Describe the solution you'd like**
Add To Cart should be present on ProductTile.

**Comment by treoden** [comment]
Hi @Jokara998 ,

I would suggest to leave it to the theming based. You can easily add a "Add to cart" button in the listing page by creating a component in your theme. Something like this:

`themes/<yourtheme>/pages/all/BuyNow.jsx`

`import Button from '@components/common/form/Button';
import React from 'react';
import { toast } from 'react-toastify';

export default function BuyNow({areaProps: {product}, action}) {
  const [adding, setAdding] = React.useState(false);
  return <Button
  className="bg-primary text-white"
  title="Add Now"
  onAction={async () => {
    setAdding(true);
    // use fetch to call the action api with the product id and quantity 1
    // then show a toast message
    const response = await fetch(action, {
      method: 'POST',
      body: JSON.stringify({
        sku: product.sku,
        qty: 1
      }),
      headers: {
        'Content-Type': 'application/json'
      }
    });
    const json = await response.json();
    if(json.error) {
      toast.error(json.error.message);
    } else {
      toast.success('Added to cart');
    }
    setAdding(false);
  }}
  isLoading={adding}
  />
}

export const layout = {
  areaId: "productListingItem",
  sortOrder: 100
}

export const query = \`
  query Query {
    action:url (routeId: "addMineCartItem")
  }
\`;
`

**Comment by Jokara998** [comment]
Hi @treoden.
Okay I will go with your suggestion.
Thanks xD.

**Comment by treoden** [comment]
Hi @Jokara998 

The fix I committed to this ticket is for adding SKU to the FeaturedProducts component.
You can also overwrite this component from your theme and add SKU

Thanks

**Comment by Jokara998** [comment]
Hi @treoden, that is great. Thank you very much.
