### ISSUE TITLE
[BUG] Add to Cart - Popup Closing

### ISSUE THREAD

**Issue by Jokara998** [evershopcommerce/evershop#325]
**Describe the bug**
When I add to the cart 2 times in a row from PDP, the app shows 2 popups. When I click on the close button on the last one, both of them are closed.
Also, this happens if there are 3 popups, 2 gets closed when I want to close the last one of them.

**To Reproduce**
1. Go to PDP
2. Click on Add to Cart 2 times
3. Two popups are displayed
4. Click on the x button on last popup
5. Both of them get closed

**Expected behavior**
Only one popup should be closed.

**Background (please complete the following information):**
-NodeJS Version: 14.18.2
-Postgres Version: 13
-EverShop Version: 1.0.0-rc.7
-OS: Ubuntu 20.04
-Browser Chrome

**Additional context**
It would be nice UX if popups would close automatically after some period of time (for example 5s).

**Comment by sahith29s** [comment]
Can I work on this issue?
