### ISSUE TITLE
[BUG] Qty input on PDP

### ISSUE THREAD

**Issue by Jokara998** [evershopcommerce/evershop#326]
**Is your feature request related to a problem? Please describe.**
Users can type nonnumber values in qty picker input on PDP. 
When validation is triggered it shows a message with regex. Many users can't really understand regex.

**Describe the solution you'd like**
Qty input should have the type of number and only accept positive numbers. 
I would suggest a better validation message that would improve UX.

**Comment by treoden** [comment]
Fixed in `1.0.0-rc.8`. Thanks
