### ISSUE TITLE
[BUG] Vulnerabilities Found in Evershop

### ISSUE THREAD

**Issue by MarioTeixeiraCx** [evershopcommerce/evershop#328]
Hello @treoden,

I hope you're doing well.

I'm a security analyst with Checkmarx's CxResearch group, and I wanted to bring to your attention some vulnerabilities we've reported to your inbox since we haven't received any response.

We'd much prefer to address these concerns privately, so we're hoping you can suggest a way for us to do that.

We appreciate your attention to this matter.

Best regards,
Mário Teixeira

**Comment by treoden** [comment]
Hi @MarioTeixeiraCx ,

Let me check the email and response to you.
Thank you so much

**Comment by MarioTeixeiraCx** [comment]
Thank you!

**Comment by MarioTeixeiraCx** [comment]
Thank you very much for your response @treoden, I will now close the Issue.
