### ISSUE TITLE
[BUG] Type Error: hasPassword

### ISSUE THREAD

**Issue by dev-ST-IA** [evershopcommerce/evershop#343]
**To Reproduce**
1. Go to packages/evershop/bin/install/index.js
2. Observe line '21' - it attempts to destructure 'hasPassword' from '@evershop/evershop/src/lib/util/passwordHelper'
3. Now go to '@evershop/evershop/src/lib/util/passwordHelper'
4. Observe the module - it doesn't have a 'hasPassword' method
**Expected behavior**
hasPassword needs to be 'hashPassword' which comes from '@evershop/evershop/src/lib/util/passwordHelper'

**Additional context**
Due to this problem, 'npm run setup' fails

**Comment by treoden** [comment]
Fixed in `1.0.0-rc.8`. Thanks
