### ISSUE TITLE
[FEATURE REQUEST] Include VAT/TAX in product prices on storeFront

### ISSUE THREAD

**Issue by ultimate-tester** [evershopcommerce/evershop#349]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
In the Dutch market (and many other European and Asian countries) it's normal to have VAT/TAX included in the prices you see in stores and webshops. It would be great to have a global checkbox in the admin panel to already calculate the tax in the price displayed on the frontStore.

So, if I set the price in admin panel for a product to 10 euros with 21% tax I want the frontStore to show 12,10 euros. For checkout and invoices, the price can be shown without VAT because it is an extra line that shows the total VAT of the order. (In other words, that can remain as it is).

**Describe alternatives you've considered**
There's no working alternative, because no matter what at the checkout an additional tax round is done.

**Comment by treoden** [comment]
Hi @ultimate-tester ,

This feature is available in `1.0.0-rc.8`. You can enable taxed price by adding below configuration to the json config file:

```
"pricing": {
        "tax": {
            "display_catalog_price_including_tax": true,
            "display_checkout_price_including_tax": true
        }
}
```

Thanks
