### ISSUE TITLE
[FEATURE REQUEST] Convert to NextJs

### ISSUE THREAD

**Issue by moshejs** [evershopcommerce/evershop#351]
**Is your feature request related to a problem? Please describe.**
Current solution uses NodeJS and ReactJS, was curious of a port to NextJS is in the works

**Describe the solution you'd like**
Use a full-stack platform to keep everything tidy

**Describe alternatives you've considered**
There are other options like Astro.

**Comment by treoden** [comment]
Hi @moshejs,

EverShop only need a front-end framework and pure React works well for now. EverShop supports server side rendering and that why I don't think we will convert it to NextJS. 

Thanks for your suggestion
