### ISSUE TITLE
[BUG] Admin graph overflows

### ISSUE THREAD

**Issue by ultimate-tester** [evershopcommerce/evershop#353]
**Describe the bug**
Graph on admin panel dashboard overflows on smaller screen

**To Reproduce**
Make the browser window a bit smaller and go to the admin panel dashboard. The graph will overflow.

**Expected behavior**
The graph should be responsive and size accordingly.

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/580758/70899753-189a-4982-a7a8-98c71a7deb36)

**Additional context**
I could pick this up and submit PR.

**Comment by ultimate-tester** [comment]
Forgot to mention, I created a PR for this.

**Comment by treoden** [comment]
Fixed in 1.0.0-rc.8. Thanks @ultimate-tester
