### ISSUE TITLE
[BUG] Fallback product images not showing in add-popup and shopping cart

### ISSUE THREAD

**Issue by ultimate-tester** [evershopcommerce/evershop#357]
**Describe the bug**
When products do not have an image, a default fallback image will be used. This is shown in the product listing pages and on the product page itself. However, when adding this product to the cart, the popup will not show the image. Also inside the shopping cart the image will not show. It will show the text of the HTML label property instead.

**To Reproduce**
1. Create a product without adding images
2. Go to product page, verify you see fallback image
3. Add the product to the cart, no image is shown in popup
4. Go to your shopping cart, no image is shown for the relevant product

**Expected behavior**
The fallback image should be used in every location where a product image is shown.

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/580758/de534356-32a5-49ce-a70d-8f9cd3aa31c9)
![image](https://github.com/evershopcommerce/evershop/assets/580758/38bed4bb-5f24-48dc-9c79-9b13bc7c5c5b)

**Additional context**
I can pick this up and submit a PR.

**Comment by ultimate-tester** [comment]
Update: while investigating why this happens, I see that it might be the product page and listing that's doing it wrong. I need some advise. The shopping cart and the popup are referring to a placeholder.png image (which does not exist in my theme). Meanwhile, the product and listing have an internal SVG code (which also appears in the shopping cart and listing, but it's never used because there's always the placeholder.png default).

What would you say is the correct approach? Use the SVG everywhere or use the placeholder.png everywhere?

**What if we use placeholder.png**
- Shown in multiple places with different big or small sizes, scaling will cause low quality image
- Easy to modify in theme

**What if we use SVG**
- Scales perfectly
- Hard to modify in the theme since it's hardcoded in multiple places

My suggestion: use the SVG everywhere but make it a shared component which is referred from everywhere this placeholder SVG is needed. Remove the "placeholder.png" references, do SVG instead. Please let me know what you think and I can create this and submit a PR.

**Comment by ultimate-tester** [comment]
Created a PR just now :)

**Comment by treoden** [comment]
Fixed in `1.0.0-rc.8`. Thanks @ultimate-tester
