### ISSUE TITLE
Tax calculation broken (show as 0.00) as of 1.0.0-rc.8

### ISSUE THREAD

**Issue by ultimate-tester** [evershopcommerce/evershop#368]
**Describe the bug**
Tax is shown as 0.00 in the shopping cart and checkout. Tax is correctly shown on product page and catalog. After selecting shipment method, tax calculation is correct.

**To Reproduce**
1. Create product and put it in a tax category higher than 0
2. Add the product to shopping cart
3. Go into the shopping cart, tax shows as 0.00
4. Checkout, tax still shows as 0.00

**Expected behavior**
Tax should be calculated properly throughout the entire shop. In this case, the product has a 21% tax but the calculation shows there's 0.00 euro tax.

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/580758/297148fc-0ddf-49d6-b5d3-b2ba75a7ba91)

**Background (please complete the following information):**
 - EverShop Version: 1.0.0-rc.8

**Additional context**

**Comment by treoden** [comment]
Hi @ultimate-tester ,

Can you share the tax setting? Are you calculating the tax based on the shipping address?

Thanks

**Comment by ultimate-tester** [comment]
Thanks for replying so fast, here is the configuration screenshot:

![image](https://github.com/evershopcommerce/evershop/assets/580758/b7f41045-8610-44bc-9a54-88ad0a28c7d8)

**Comment by ultimate-tester** [comment]
Okay after looking at more code it seems that the catalog + product pages are using the store's country to `getTaxRates`. The shopping cart and order summary are using the customer's country to `getTaxRates`.

My suggestion is to modify the getTaxRates function, to make the country, province and postalcode optional. If they are null, it will use the store's country, province and postalcode as a fallback. This means that it will be able to show a tax amount even if the customer did not enter their address yet. It will then update the correct tax rate once the customer enters their address and that will be the final price.

If appreciated, I can submit a PR for this.

**Comment by ultimate-tester** [comment]
Can be closed. My mistake, I did not set the Tax Basic Configuration in admin panel:
![image](https://github.com/evershopcommerce/evershop/assets/580758/01417ef6-a625-41df-86ce-4d155df5fca2)
