### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by myloverhxx** [evershopcommerce/evershop#372]
clone main branch
install dependiences...

1、when run sudo npm run build
result:
> evershop@1.0.0-beta build
> evershop build

✖ Client
  Compiled with some errors in 389.21ms

● Server █████████████████████████ sealing (92%) asset processing 
 TerserPlugin

✖ Client
  

✖ Server
  Compiled with some errors in 384.01ms

❌ Error: Error message must be a string or an Error object
    at error (/Users/username/Documents/code/evershop/packages/evershop/src/lib/log/debuger.js:54:11)
    at /Users/username/Documents/code/evershop/packages/evershop/bin/build/complie.js:16:9
    at /Users/username/Documents/code/evershop/packages/evershop/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/username/Documents/code/evershop/packages/evershop/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
    
2、 when run sudo npm run start:debug
> evershop@1.0.0-beta start:debug
> evershop start --debug

✅ 
   ┌─────────────────────── EverShop ───────────────────────┐
   │                                                        │
   │   Your website is running at "http://localhost:3000"   │
   │                                                        │
   └────────────────────────────────────────────────────────┘

[debug] ℹ️ [GET] /
-> Middleware context - 0.234958 ms
-> Middleware detectCurrentCart - 1.151792 ms
-> Middleware auth - 0.011834 ms
-> Middleware meta - 0.062542 ms
-> Middleware bodyParser - 0.065875 ms
-> Middleware addCustomerToCart - 0.005791 ms
-> Middleware buildQuery - 2.11325 ms
-> Middleware graphql - 22.963083 ms
-> Middleware notification - 0.006375 ms
-> Middleware notFound - 0.005209 ms
-> Middleware response - 0.25875 ms

[debug] ❌ Cannot find module '/Users/username/Documents/code/evershop/.evershop/build/frontStore/homepage/server/index.js'
Require stack:
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/response/render.js
- /Users/username/Documents/code/evershop/packages/evershop/src/modules/base/pages/global/response[errorHandler].js
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/middleware/buildMiddlewareFunction.js
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/middleware/parseFromFile.js
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/middleware/Handler.js
- /Users/username/Documents/code/evershop/packages/evershop/bin/lib/startUp.js
- /Users/username/Documents/code/evershop/packages/evershop/bin/start/index.js
- /Users/username/Documents/code/evershop/packages/evershop/bin/evershop
Error: Cannot find module '/Users/username/Documents/code/evershop/.evershop/build/frontStore/homepage/server/index.js'
Require stack:
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/response/render.js
- /Users/username/Documents/code/evershop/packages/evershop/src/modules/base/pages/global/response[errorHandler].js
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/middleware/buildMiddlewareFunction.js
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/middleware/parseFromFile.js
- /Users/username/Documents/code/evershop/packages/evershop/src/lib/middleware/Handler.js
- /Users/username/Documents/code/evershop/packages/evershop/bin/lib/startUp.js
- /Users/username/Documents/code/evershop/packages/evershop/bin/start/index.js
- /Users/username/Documents/code/evershop/packages/evershop/bin/evershop
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at renderProduction (/Users/username/Documents/code/evershop/packages/evershop/src/lib/response/render.js:85:26)
    at render (/Users/username/Documents/code/evershop/packages/evershop/src/lib/response/render.js:109:5)
    at module.exports (/Users/username/Documents/code/evershop/packages/evershop/src/modules/base/pages/global/response[errorHandler].js:55:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async asyncMiddlewareWrapper (/Users/username/Documents/code/evershop/packages/evershop/src/lib/middleware/async.js:36:5)
    
    **version**
    node v18.8.0 , npm 9.5.1 , pgsql 15
    
    **config/production.json**
```json
{
    "shop" : {
        "currency": "USD",
        "language": "cn",
        "weightUnit": "kg"
    },   
    "catalog": {
        "product": {
            "image": {
                "thumbnail": {
                    "width": 100,
                    "height": 100
                },
                "listing": {
                    "width": 300,
                    "height": 300
                },
                "single": {
                    "width": 500,
                    "height": 500
                }
            }
        },
        "showOutOfStockProduct": false
    },
    "system": {
        "theme": "friday",
        "extensions": []
    }
}
``` 

**jsconfig.json**
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components/*": [
        // "./themes/friday/components/*",
        // "./extensions/productComment/components/*",
        "./packages/evershop/src/components/*"
      ],
      "@components-origin/*": [
        "./packages/evershop/src/components/*"
      ],
      "@default-theme/cms/*" : [
        "./packages/evershop/src/modules/cms/pages/*"
      ],
      "@evershop/evershop/*" : [
        "./packages/evershop/*"
      ]
    }
  }
}

```

I appreciate your time and consideration. I hope to hear from you at your earliest convenience. Thank you!

**Comment by treoden** [comment]
Hi @myloverhxx ,

Can you try "npm run build --skip-minify"?

Thanks

**Comment by abdallahhelmy99** [comment]
I have the same issue 

`sudo npm run start:debug



> my-app@0.1.0 start:debug
> evershop start --debug

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

✅
   ┌─────────────────────── EverShop ───────────────────────┐
   │                                                        │
   │   Your website is running at "http://localhost:3000"   │
   │                                                        │
   └────────────────────────────────────────────────────────┘


WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
[debug] ❌ Cannot find module '/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/.evershop/build/frontStore/homepage/server/index.js'
Require stack:
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/response/render.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/modules/base/pages/global/response[errorHandler].js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/middleware/buildMiddlewareFunction.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/middleware/parseFromFile.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/middleware/Handler.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/bin/lib/startUp.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/bin/start/index.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/bin/evershop
Error: Cannot find module '/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/.evershop/build/frontStore/homepage/server/index.js'
Require stack:
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/response/render.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/modules/base/pages/global/response[errorHandler].js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/middleware/buildMiddlewareFunction.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/middleware/parseFromFile.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/middleware/Handler.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/bin/lib/startUp.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/bin/start/index.js
- /Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/bin/evershop
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at renderProduction (/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/response/render.js:85:26)
    at render (/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/response/render.js:109:5)
    at module.exports (/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/modules/base/pages/global/response[errorHandler].js:55:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async asyncMiddlewareWrapper (/Users/abdallahhelmy/Abdallah's/Mine/Work/evershop-manual/my-app/node_modules/@evershop/evershop/src/lib/middleware/async.js:36:5)
[debug] ℹ️ [GET] /
-> Middleware context - 0.919291 ms
-> Middleware detectCurrentCart - 60.557166 ms
-> Middleware auth - 0.166541 ms
-> Middleware meta - 9.665708 ms
-> Middleware bodyParser - 10.750125 ms
-> Middleware addCustomerToCart - 0.100208 ms
-> Middleware buildQuery - 4.904458 ms
-> Middleware graphql - 72.792708 ms
-> Middleware notification - 0.008791 ms
-> Middleware notFound - 0.027166 ms
-> Middleware response - 0.2055 ms

`

**Comment by treoden** [comment]
Hi @abdallahhelmy99 ,

You are starting the app in production mode, You must run the build command first: "npm run build"

**Comment by xiaofeimaoIan** [comment]
> Hi @myloverhxx ,
> 
> Can you try "npm run build --skip-minify"?
> 
> Thanks

I have tried to run "npm run build --skip-minify", but I still get the same error
![error](https://github.com/evershopcommerce/evershop/assets/150426398/dffff488-3f15-46a0-a237-45c83e7a7c2e)

**package.json**
`{
  "name": "hyggetimes",
  "version": "0.1.2",
  "private": true,
  "scripts": {
    "setup": "evershop install",
    "build": "evershop build --skip-minify",
    "start": "evershop start ",
    "start:debug": "evershop start --debug",
    "dev": "evershop dev",
    "user:create": "evershop user:create",
    "user:changePassword": "evershop user:changePassword"
  },
  "dependencies": {
    "@evershop/evershop": "1.0.0-rc.8",
    "@evershop/google_login": "^1.0.0",
    "@evershop/product_review": "^1.0.1",
    "@evershop/sendgrid": "^1.0.0",
    "@headlessui/react": "^1.7.18",
    "@heroicons/react": "^1.0.5",
    "@paypal/paypal-js": "^8.0.0",
    "nodemailer": "^6.9.7",
    "react-paginate": "^8.2.0",
    "swiper": "^11.0.3",
    "tailwindcss": "^3.4.1"
  },
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "description": "",
  "workspaces": [
    "extensions/*"
  ]
}
`
Please help me, thank you very much

**Comment by treoden** [comment]
Hi @myloverhxx ,

You are using outdated version of EverShop. Please use the latest version (1.0.0)

Thanks

**Comment by xiaofeimaoIan** [comment]
> Hi @myloverhxx ,
> 
> You are using outdated version of EverShop. Please use the latest version (1.0.0)
> 
> Thanks

Hi @myloverhxx ,
Can you tell me what causes this? There is no problem running, packaging this error.
Thanks

**Comment by treoden** [comment]
Hi @xiaofeimaoIan ,

You can just install the latest version and try again: `npm install @evershop/evershop@latest`

**Comment by xiaofeimaoIan** [comment]
> Hi @xiaofeimaoIan ,
> 
> You can just install the latest version and try again: `npm install @evershop/evershop@latest`

Hi @treoden ,
Because I overwrote some native components, I was unable to use the latest version, and the following error occurred when packaging with the latest version.
![error](https://github.com/evershopcommerce/evershop/assets/150426398/f2f08405-5811-4b8e-b5a0-05c4b5a2fcea)

Thanks

**Comment by treoden** [comment]
Hi @xiaofeimaoIan ,

From the screenshot, look like you are importing a module and Node can not find it. I suggest you to check again the path

**Comment by xiaofeimaoIan** [comment]
> Hi @xiaofeimaoIan ,
> 
> From the screenshot, look like you are importing a module and Node can not find it. I suggest you to check again the path

Hi @treoden ,

Thank you for your reply. I have solved my problem.
