### ISSUE TITLE
[QUERY] Starting in dev mode- self signing certificate error

### ISSUE THREAD

**Issue by trilloc** [evershopcommerce/evershop#379]
**Describe the bug**
npm run dev gives the error below:

![image](https://github.com/evershopcommerce/evershop/assets/63382707/659cd89c-2da0-487b-ae43-827d513aa3ea)

**To Reproduce**
run npm run dev

**Expected behavior**
Start the evershop development server and client

**Screenshots**
Added above

**Comment by trilloc** [comment]
Thanks. I turned off ssl in postgresql.conf and removed the DBSSL configuration in .env. Now it is starting up.

**Comment by treoden** [comment]
Hi @trilloc 

The reason is you are using self-signed cert and it is not in the trusted list. 
You have some options:
1: Turn off the SSL and add environment "DB_SSLMODE" = "disabled"
2: Set the environment "DB_SSLMODE" = "no-verify"

Thanks
