### ISSUE TITLE
[BUG] Best sellers wrong currency and without tax

### ISSUE THREAD

**Issue by ultimate-tester** [evershopcommerce/evershop#380]
**Describe the bug**
In admin panel, the "best sellers" widget on the dashboard always shows dollar currency symbol regardless of the setting. Also, the shown amount does not include tax.

**To Reproduce**
1. Go to admin panel
2. Go to dashboard
3. Look at best sellers widget

**Expected behavior**
The best seller widget should adhere to currency setting, and also include the relevant tax based on tax category.

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/580758/295eb5da-84a5-429e-8253-3bb2ae17cfcc)

I'm happy to fix this bug and submit PR, please assign the issue to me :)

**Comment by ultimate-tester** [comment]
@treoden  it's done 👍

**Comment by treoden** [comment]
Fixed. Closing
