### ISSUE TITLE
Create DATABASE if not exist in Installscript 

### ISSUE THREAD

**Issue by el-j** [evershopcommerce/evershop#381]
**Is your feature request related to a problem? Please describe.**
when running the fresh install script 
```
npx create-evershop-app my-app
```
the script fails when the database itself does not exist.

**Describe the solution you'd like**
```
IF script gets the right credentials for the postgres-Host
AND the database does not exist
CREATE the database with name on the postgres-host
```
**Describe alternatives you've considered**
i dont see any alternative

**Additional context**
this is very anyoing if you just wanna quick start with evershop. it is somehow a show stopper as
you have to create the database on your own. 
running a "start and installscript" should solve this problem on its own.

<img width="986" alt="Screenshot 2023-10-31 at 11 37 13" src="https://github.com/evershopcommerce/evershop/assets/2795534/dfbdda19-53a0-428b-82dd-173d2949fdf7">

**Comment by treoden** [comment]
Hi @el-j ,

Creating a database sometime requires different level of permission, so that is why we let user create it before running the installation script. Thanks for your pr but I will close it for now
