### ISSUE TITLE
[ISSUE] Unable to upload images for new category 

### ISSUE THREAD

**Issue by trilloc** [evershopcommerce/evershop#385]
**Describe the bug**
**Unable to upload images for new category.** 

After git clone of this repository, I ran npm run setup and npm run build and npm run start and npm run create:user

After that I logged in to the admin console and tried to create a new category. Got the error in the screenshot.

(This error happens even after I create the production.json in the config directory)

**To Reproduce**
1. Git clone
2. npm run setup
3. npm run build
4. npm run start

**Expected behavior**
Should be able to upload images. 

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/63382707/d4c7186d-1060-4bf6-a1f7-33803c98d412)

![image](https://github.com/evershopcommerce/evershop/assets/63382707/4fe1788c-cb32-4c94-b586-8b15e0e64b88)

**Comment by ultimate-tester** [comment]
This functionality works fine for me. Do you have a media folder in the root with permission to access and write to it?

**Comment by trilloc** [comment]
Did you clone the repo or use npx to install it?

Cheers

**Comment by trilloc** [comment]
I still get the error 

e.data is not defined

or response.data is not defined :(

**Comment by ultimate-tester** [comment]
If you did a git clone (and used the dev branch), this might just be caused by the new cloud functionality which is still work in progress. This would explain why I don't have this issue, as I am on a stable release.

Try to use `npx create-evershop-app my-app` to create a new evershop instance.

**Comment by trilloc** [comment]
Ok great. I would like to make some modifications to the code.. how do i install the source?

**Comment by ultimate-tester** [comment]
Your approach is indeed the correct approach on getting the source for development purposes. If you used the main branch it should be good without error. There is a separate dev branch, which is unstable.

Are you running on Windows? I can try to recreate the error you got.

**Comment by trilloc** [comment]
I am running on WSL Ubuntu on Windows..  Thanks for your efforts!

**Comment by ultimate-tester** [comment]
This is undocumented, but seems to be caused by the cloud storage functionality. Put the following in your configuration file:

`"file_storage": "local"`

@treoden if I may kindly suggest, could you write the if statements in such a way that "local" is the default/fallback option for `file_storage`, even if it is not set? For example the if statement in `packages\evershop\src\modules\cms\api\fileBrowser\browser.js` will give unexpected behavior if `file_storage` is not set in the configuration file, which it won't for all old users.

**Comment by treoden** [comment]
Hi @trilloc , @ultimate-tester 

This is the work in progress. I am taking a look to this now. Thanks

**Comment by trilloc** [comment]
> This is undocumented, but seems to be caused by the new cloud storage functionality. Put the following in your configuration file:
> 
> `"file_storage": "local"`
> 
> @treoden if I may kindly suggest, could you write the if statements in such a way that "local" is the default/fallback option for `file_storage`, even if it is not set? For example the if statement in `packages\evershop\src\modules\cms\api\fileBrowser\browser.js` will give unexpected behavior if `file_storage` is not set in the configuration file, which it won't for all old users.

That worked!! Thanks a ton!

**Comment by treoden** [comment]
Hi @trilloc 

You can pull the latest update. The config is now moved to "system":

`
"system": {
  "file_storage": "local"
}
`
Thanks
