### ISSUE TITLE
[EXCEPTION] Unable to add customer address schema to config file

### ISSUE THREAD

**Issue by trilloc** [evershopcommerce/evershop#386]
**Describe the bug**
Adding the customer schema to config file throws an error.

**To Reproduce**
Copy "Customer Address Schema" JSON from the Configuration Guide (https://evershop.io/docs/development/knowledge-base/configuration-guide) to the config file. When npm run start is done, it throws an error.

**Expected behavior**
Customer Address Schema is shown to customer during the checkout process.

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/63382707/2d93271c-1828-4023-b91e-68401e2f44cb)

**Comment by ultimate-tester** [comment]
So I do see that the example config would be invalid json. Try wrapping every property into double quotes, and also converting the single quoted string values to double quotes. Next, all values using "translate" within errorMessage key are invalid too. Just put the string value directly next to the key (e.g. `"full_name": "Full name is required",`)

**Comment by trilloc** [comment]
The "stringing" of the keys and values worked..!!
