### ISSUE TITLE
[BUG] Randomly does not show accept/show images for catalog

### ISSUE THREAD

**Issue by trilloc** [evershopcommerce/evershop#390]
**Describe the bug**
When an image is uploaded for a product, it does not sometimes show up in the listing. If an image is deleted and reselected, then it shows up .. in a random fashion.

**To Reproduce**
1. Create new product
2. Upload media or image in description

**Expected behavior**
Uploaded Image should show up in the listing / frontpage / catalog item.

**Comment by treoden** [comment]
Hi @trilloc ,

Here is how the product image works:

When you upload an image, the original version will be saved, and then EverShop has a subscriber running at the background to take the original version, resize it and produces 3 more versions (Listing, thumbnail and single). This will help to prevent loading the original version (big) all the time. 

So After you upload an image, wait for some seconds and the thumbnail will be generated for the listing

**Comment by trilloc** [comment]
Hi
Thanks for the info.. I did observe that it updates after a few seconds..
however some of the products did not update at all even after several tries
to upload and after waiting for many minutes..

Rgds

**Comment by SpacewormSera** [comment]
I have the same problem. Just started to use it, and no image after more that 10 minutes so far

**Comment by evershopcommerce** [comment]
Hi @SpacewormSera ,

You cloned the source from this repo or installed from npm?

**Comment by SpacewormSera** [comment]
> Hi @SpacewormSera ,
> 
> You cloned the source from this repo or installed from npm?

Hi @evershopcommerce, I cloned it from this repo and followed the first installation steps, basically created Postgres, and npm setup + build

**Comment by treoden** [comment]
Hi @SpacewormSera ,

When did you clone the source, We have pushed some fixes. Can you pull the latest and try again?

**Comment by treoden** [comment]
Hi @SpacewormSera ,

Please ignore my previous comment, I am able to reproduce the issue and checking it now.

**Comment by SpacewormSera** [comment]
Hi treoden, thanks for fixing it, now it works! Of course I had to add the products again

**Comment by treoden** [comment]
Fixed. Closing
