### ISSUE TITLE
[BUG] DOCs not right for PRODUCT API

### ISSUE THREAD

**Issue by el-j** [evershopcommerce/evershop#393]
**Describe the bug**
In the [Docs](https://evershop.io/docs/api/product#create-a-product) for the Product, 
the field `images` has the wrong naming. it's `image` without the s.

as well it's not possible to sent an array of image urls to the database

**To Reproduce**
1. Create a "Product" as json  
2. Send it as Post to the Product-Api as described in the docs
3. check the product-table in postgres
4. nothing is stored in the "image" field

**Expected behavior**
the string or the array of images should be stored in the database.

**Screenshots**
<img width="845" alt="image" src="https://github.com/evershopcommerce/evershop/assets/2795534/1e87ed37-b492-432f-ab71-f3079d6549a5">

**Background (please complete the following information):**
 - NodeJS lts/hydrogen v18.18.0
 - Postgres 16
 - EverShop 1.0.0-rc.8

**Additional context**
I testing evershop to finally leave shopware behind. therefor i need to insert all products from a CSV. so i need to use the products-POST-API to get the store filled. i am currently writing a little admin extension for the upload. but it seems to be not possible to post a simple image or an array of images. When i change the field name from "images" to "image" the string gets stored to the database, but the image is not shown in the admin panel-prodcuts nor in the frontshop.
is it possible to use external image-urls as well. Help is very much appreciated .

**Comment by evershopcommerce** [comment]
Hi @el-j , 

We are working on the file storage with some change to the way of storing product images. We will update the docs soon. Thanks

**Comment by el-j** [comment]
hi, in the meanwhile i have written my self a little extension, that looks into the images and if they are an url, it downloads the images and puts them to the normal process. so thumbnails and everything gets created as needed.
```jsx
const https = require("https");
async function download(url, dest) {
  console.log("url", url, "dest", dest);
  var file = createWriteStream(dest);
  return new Promise((resolve) =>
    https
      .get(url, function (response) {
        response.pipe(file);
        file.on("finish", function () {
          file.close(resolve()); 
        });
      })
      .on("error", function (err) {
        unlink(dest); // Delete the file async. (But we don't check the result)
      })
  );
}
```

and call it somewhere after the product is created. where url is the encoded url to the image:
```jsx
await download(url, path.join(CONSTANTS.MEDIAPATH, targetPath, imageName));
```

maybe it helps :)

**Comment by treoden** [comment]
Hi @el-j ,

I think the docs is right. The `images` is an array with list of image url. Thanks
