### ISSUE TITLE
[QUERY] Is it possible to enable Google Authentication?

### ISSUE THREAD

**Issue by trilloc** [evershopcommerce/evershop#394]
Hi @treoden @ultimate-tester !

Is it possible to enable google authentication for evershop? Pls do let me know.

Thanks a lot!

Cheers
Rajesh

**Comment by ultimate-tester** [comment]
https://www.npmjs.com/package/@evershop/google_login

Is that what you're looking for?

**Comment by trilloc** [comment]
> https://www.npmjs.com/package/@evershop/google_login
> 
> Is that what you're looking for?

Hi.. I npminstalled this, and put the extension and clientid/secret in the json file, but it is not showing a Google login.. Is there anything else that needs to be done?

Rgds
Rajesh

**Comment by trilloc** [comment]
BTW, I also did the npm run build.. but the Google Signin is not showing up in the signup or signin screen..

**Comment by treoden** [comment]
Hi @trilloc ,

If you do it correctly, a button for Google login will be displayed in the login form. 

Can you show the extension config? And did you make any modification to the default login form? 

Thanks

**Comment by trilloc** [comment]
Hi @treoden 

here it is.. I did not change the default login form.. (again.. i cloned the repo.. so it is not the npx installed one..)

{
    "shop" : {
        "currency": "INR",
        "language": "en",
        "weightUnit": "kg",
    },   
    "catalog": {
        "product": {
            "image": {
                "thumbnail": {
                    "width": 100,
                    "height": 100
                },
                "listing": {
                    "width": 300,
                    "height": 300
                },
                "single": {
                    "width": 500,
                    "height": 500
                }
            }
        },
        "showOutOfStockProduct": false
    },
    "system": {
        "file_storage": "local",
        "theme": "friday",
        "extensions": [
		            {
                "name": "razorpay",
                "resolve": "node_modules/evershop-razorpay/razorpay",
                "enabled": true
            }
        ]
    },
    "extensions": [
        {
          "name": "google_login",
          "resolve": "node_modules/@evershop/google_login",
          "enabled": true,
          "priority": 10
        }
      ],
      "google_login": {
        "client_id": "4......xxx.x.x.x.x.x.xapps.googleusercontent.com",
        "client_secret": "XXXSDWEWDSDDXX",
        "success_redirect_url": "http://localhost:3000",
        "failure_redirect_url": "http://localhost:3000/account/login"
      },
      "themeConfig": {
        "logo": {
            "alt": "Like$",
            "src": "/assets/logo.png",
            "width": 50,
            "height": 50
        },
        "headTags": {
            "links": [],
            "metas": [],
            "scripts": []
        },
        "copyright": "© 2023 Likes Platform. All Rights Reserved."
    }    
}

**Comment by trilloc** [comment]
Hi @treoden 

Here is the config file.. I have two extensions.. (I have not modified the default login form..)
{
    "shop" : {
        "currency": "INR",
        "language": "en",
        "weightUnit": "kg",

        "store_type": "physical",
        "branchAddress" : [{
            "code" : "1",
            "fullName": "KNK Road Branch",
            "postcode": "600006",
            "telephone": "9884701273",
            "country": { "code": "IN", "name": "India" },
            "province": { "code": "IN-TN", "name": "Tamil Nadu" },
            "city": "Chennai",
            "address1": "10, Khader Nawaz Khan Rd, Srirampuram, Thousand Lights West"
          }]
    },   
    "catalog": {
        "product": {
            "image": {
                "thumbnail": {
                    "width": 100,
                    "height": 100
                },
                "listing": {
                    "width": 300,
                    "height": 300
                },
                "single": {
                    "width": 500,
                    "height": 500
                }
            }
        },
        "showOutOfStockProduct": false
    },
    "system": {
        "file_storage": "local",
        "theme": "friday",
        "extensions": [
		            {
                "name": "razorpay",
                "resolve": "node_modules/evershop-razorpay/razorpay",
                "enabled": true
            },
        {
          "name": "google_login",
          "resolve": "node_modules/@evershop/google_login",
          "enabled": true,
          "priority": 10
        }
      ]
    },
      "google_login": {
        "client_id": "12345678899-xxxxxxxxx.apps.googleusercontent.com",
        "client_secret": "GXXXXXXXX",
        "success_redirect_url": "http://localhost:3000",
        "failure_redirect_url": "http://localhost:3000/account/login"
      },
      "themeConfig": {
        "logo": {
            "alt": "Like$",
            "src": "/assets/logo.png",
            "width": 50,
            "height": 50
        },
        "headTags": {
            "links": [],
            "metas": [],
            "scripts": []
        },
        "copyright": "© 2023 Likes Platform. All Rights Reserved."
    }    
}

**Comment by treoden** [comment]
It looks good.

Did you make any modification to the default login form? 
Google login will automatically inject a login button to the form based on the AreaID. If you make the modification, make sure to keep this AreaID

**Comment by trilloc** [comment]
Hi @treoden, I have not made any modifications to the login form.. (Again I cloned the repo to run this.. not from npx..)

The above config still doesnt work.. How do you mean to keep this AreaID?

Cheers
Rajesh

**Comment by trilloc** [comment]
It now works! my bad.. I had two json files for config.. !

Mucho thanks!

Cheers
Rajesh
