### ISSUE TITLE
[QUERY] Adding an extension to display a message in the Admin Dashboard

### ISSUE THREAD

**Issue by trilloc** [evershopcommerce/evershop#396]
Hi @ultimate-tester @treoden 

I am trying to create an extension as per your instructions on https://evershop.io/docs/development/module/create-your-first-extension.. I can see that the Area ID for the product used is productPageMiddleLeft. I am trying to add a div to the admin dashboard but the Area IDs there are leftSide and rightSide, these two seem to be there in many other modules as well. Should I make changes to the admin dashboard layout to create "adminLeftSide" etc?

Thanks for your clarifications!

Cheers
Rajesh

**Comment by treoden** [comment]
Hi @trilloc ,

You can add a component which contains another Area for your own business. Nested Area is ok.
The point is not to overwrite the core source, It will be overwritten when you upgrade a new version 

Thanks

**Comment by trilloc** [comment]
Thanks for the clarification! Do you mean I can write a component just like
another extension? How can I do that to make changes to the admin
dashboard, can you explain please.

Rgds
Rajesh

**Comment by treoden** [comment]
Hi @trilloc ,

Yes you can add a new component to the admin theme Just like the way core modules works. 
(You can not have a completed new theme like a frontStore) .

You can have a "pages/admin" folder in your extension and adding your components from there.
You can check any core modules and see how they are doing it.

Thanks

**Comment by trilloc** [comment]
Thanks again.. one more query.. is it possible to change the checkout
workflow as well using components or modules..

Cheers

**Comment by treoden** [comment]
Hi @trilloc ,

Sure, Checkout is just a page like the others (a little bit more complex for sure). You can build your own checkout page just like another one.

Thanks

**Comment by trilloc** [comment]
Thanks, I'll check it out 😊

Can I do that as an extension?

**Comment by treoden** [comment]
Hi @trilloc ,

Yes you can do it as an extension. Thanks

**Comment by trilloc** [comment]
That's very interesting, and thank you for the info.

Can you please briefly explain how do I modify existing workflow as an
extension? I thought I can only add features using extensions.

Cheers

**Comment by el-j** [comment]
@trilloc the magic just happens with the layout code.

so if you want to add something to checkout-page. create an extension with 
`extensions/checkout_enhancement/pages/frontStore/yourComponent.jsx` and adjust the layout.
 
```
export const layout = {
  areaId: 'content',
  sortOrder: 1
};
```

in my case i have an admin extension. but works the same for frontStore.
<img width="1155" alt="image" src="https://github.com/evershopcommerce/evershop/assets/2795534/5ee75bf7-2539-48d5-8a8c-4fa71bb8dc7f">

read more in the docs:
https://evershop.io/docs/development/module/create-your-first-extension
