### ISSUE TITLE
[FEATURE REQUEST] TypeScript?

### ISSUE THREAD

**Issue by j3bb9z** [evershopcommerce/evershop#414]
**Is your feature request related to a problem? Please describe.**
Are you planning to add TypeScript to this project?

**Describe the solution you'd like**
Adding TypeScript

**Describe alternatives you've considered**
None

**Additional context**
TypeScript is very helpful, especially when dealing with medium and large size projects. Contributing to that kind of project is so much easier with types. Docblocks are helpful, but it's not the same as TS. Please consider it.

**Comment by treoden** [comment]
Hi @j3bb9z ,

We will stick with Pure JS for now. 

Thanks
