### ISSUE TITLE
Unable to start project due to typos in filenames and incorrect line endings

### ISSUE THREAD

**Issue by michalvarys** [evershopcommerce/evershop#418]
Following imports doesn't match the filenames [CouponValidator](https://github.com/evershopcommerce/evershop/blob/29c834a0e25ce2152152d5a58b85923420ffb71a/packages/evershop/src/modules/promotion/services/CouponValidator.js) [DiscountCalculator](https://github.com/evershopcommerce/evershop/blob/29c834a0e25ce2152152d5a58b85923420ffb71a/packages/evershop/src/modules/promotion/services/DiscountCalculator.js) 
https://github.com/evershopcommerce/evershop/blob/29c834a0e25ce2152152d5a58b85923420ffb71a/packages/evershop/src/modules/promotion/bootstrap.js#L3-L4

```
-const { validateCoupon } = require('./services/couponValidator');
-const { calculateDiscount } = require('./services/discountCalculator');
+const { validateCoupon } = require("./services/CouponValidator");
+const { calculateDiscount } = require("./services/DiscountCalculator");
```

CRLF line ending for the file [evershop](https://github.com/evershopcommerce/evershop/blob/29c834a0e25ce2152152d5a58b85923420ffb71a/packages/evershop/bin/evershop) causes an error
```
$ evershop dev
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
```
It starts working after manually changing the line ending to LF 

Ubuntu 20.04.5 LTS; 
NPM 9.8.1;

**Comment by treoden** [comment]
Hi @michalvarys ,

Yeah, with the latest release, the name of those 2 files changed (camel cases). I think your git was not case sensitive and it does not update the file name in this case.

**Comment by claudiolor** [comment]
Hi @treoden,

I faced the same issue with importing the CouponValidator  and DiscountCalculator modules also creating a project via `npx`.

Looking at [these files in the Github repository](https://github.com/evershopcommerce/evershop/tree/main/packages/evershop/src/modules/promotion/services) it looks like they still have the Pascal case naming, so probably they still need to be renamed.

**Comment by tiberiuichim** [comment]
I created a PR for this. I find the notion of seeing this sort of issue in a release of Evershop a bit troubling and makes me raise the question: is this project right for me?

**Comment by treoden** [comment]
Hi,

That was a stupid mistake from me. Thanks for the PR @tiberiuichim
