### ISSUE TITLE
[FEATURE REQUEST] An option to calculate the shipping rate based on the distance and either the actual weight of an item or the dimensional weight of an item

### ISSUE THREAD

**Issue by Raytle** [evershopcommerce/evershop#419]
**Is your feature request related to a problem? Please describe.**
I want to be able to charge customers based on the weight, volume, and shipping distance. I am shipping large, heavy objects that will normally cost me from $75 to $1500 to ship.

**Describe the solution you'd like**
Let's say I am selling an item that is located in Chicago, Illinois 60632. Let's say I sell that to a customer living in Philadelphia, Pennsylvania 19103.

According to Google, the [distance from 60632 to 19103](https://www.google.com/search?client=firefox-b-1-lm&q=distance+from+60632+to+19103) is approximately 761 miles (1224 kilometers).

For weight I would like the option to enter....

1.  The weight of the item (for example, 621 pounds)

For volume I would like the option to enter....

1.  The width of the item (for example, 62 inches)
2.  The depth of the item (for example, 34 inches)
3.  The height of the item (for example, 71 inches)

I don’t want to take the time to create a formula now, but imagine I had created a formula which used either the actual weight of an item or the dimensional weight of a particular item (also known as the volumetric weight of the item). 

Imagine that formula had calculated the shipping rate as, $75 for the minimum shipping rate, $1.20/mile for the first range of miles, $1.05/mile for the second range of miles, $1.20/mile for the second range of miles, $0.95/mile for the third range of miles, and $0.70/mile for the fourth range of miles.

For the 621 pound item with a width 62 inches, a depth of 34 inches, and a height of 71 inches, located in Chicago, Illinois 60632 that I sold to a customer living in Philadelphia, Pennsylvania 19103, the shipping would be calculated as follows…

1. **Field 01:** Minimum shipping rate (for example, $75)
2. **Field 02:** First range of miles (for example, $1.20/mile for the first 250 miles, covering 50 miles to 300 miles)
3. **Field 03:** Second range of miles (for example, $1.05/mile for the next 274 miles, covering 301 miles to 575 miles)
4. **Field 04:** Third range of miles (for example, $0.95/mile for the next 186 miles, covering 576 miles to 761 miles)

That would work out to…

1. **Field 01:**  $75 for the minimum shipping price 
2. **Field 02:** $1.20/mile * 250 miles (because 300 miles - 50 miles = 250 miles)
3. **Field 03:** $1.05/mile * 274 miles (because 575 miles - 301 miles = 274 miles)
4. **Field 04:** $0.95/mile * 186 miles (because 761 miles - 575 miles = 186 miles)

Therefore, the total shipping would be approximately $839 because 
$839 ≈ $75 + ($1.20/mile * 250 miles) + ($1.05/mile * 274 miles) + ($0.95/mile * 186 miles).

**Describe alternatives you've considered**
I have not considered any alternatives.

**Additional context**
I don’t have any additional context.

**Comment by treoden** [comment]
Hi @Raytle ,

For this kind of unique logic, I suggest you build your own API for cost calculation. Evershop supports you to specified the API for cost calculation from the setting
![image](https://github.com/evershopcommerce/evershop/assets/6950941/78b6e46c-698f-4d9a-8f3d-0abf79b7aaf6)

Thanks

**Comment by Raytle** [comment]
Cool. Thanks!

**Comment by treoden** [comment]
Hi @Raytle ,

We just released a new version v1.1.0. You can now define the shipping cost base on the total or weight of the order.
It does not allow you to define a distance but I think you can use the shipping zone location to handle it
Thanks

**Comment by Raytle** [comment]
Thanks for letting me know.
