### ISSUE TITLE
[BUG] Missing {position} Category - Menu Item

### ISSUE THREAD

**Issue by edyrkaj** [evershopcommerce/evershop#420]
**Describe the bug**
The `GraphQL` call is missing the property `position` which can be used to sort menu / categories in the FrontStore.

- it can be useful to sort the menu items based on the position value. 
- also, it is missing on the Admin panel to edit or change the value / but exists in the DB structure.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="931" alt="image" src="https://github.com/evershopcommerce/evershop/assets/2579367/5d888631-d6c7-4c21-8caf-7fe3c09bec83">

**Background (please complete the following information):**
 - NodeJS Version
 - Postgres Version
 - EverShop Version
 - OS: [e.g. Window, Ubuntu, Mac-OS]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by treoden** [comment]
Hi @edyrkaj ,

Thanks for your suggestion. For now we can assign both category and cms page to the menu.
For category, we can use the sort_order field (available for category). However we do not have it for cms page.

Can I suggest you build your own menu manager as an extension?

Thanks
