### ISSUE TITLE
[BUG]Cannot query field "alt" on type "CategoryImage".

### ISSUE THREAD

**Issue by chendind** [evershopcommerce/evershop#423]
**Describe the bug**
When open https://shop.sohoyo.io/kids
Page shows:
Cannot query field "alt" on type "CategoryImage".

**Screenshots**
![WX20240101-003043@2x](https://github.com/evershopcommerce/evershop/assets/9668199/81a8a1d9-ec4c-4780-9777-b2c2a33e8c08)

**Background (please complete the following information):**
 - NodeJS Version: node:18-alpine
 - Postgres Version: postgres:16
 - EverShop Version: latest
 - OS: [e.g. Window, Ubuntu, Mac-OS]: my server is ubuntu 22.24, my pc is Mac-OS
 - Browser [e.g. Chrome, Safari]: Chrome

**Additional context**
I downloaded the latest code, then ran `npm run build` locally (Mac OS, node 18.16.0, npm 9.5.1) to package, updated the .evershop generated by the packaging into the docker container, and then restarted the container

Some pages will have various error reports

**Comment by chendind** [comment]
And also, when enter admin to edit commodities...

![WX20240101-003043@2x](https://github.com/evershopcommerce/evershop/assets/9668199/940ac272-0a56-48a1-9ac6-98b8ccefc0fd)

**Comment by treoden** [comment]
Hi @chendind ,

I checked the link you share and no error. I also tried on my local and can not re-produce the error. Let me know if the error still persist from your end. 
Thanks

**Comment by chendind** [comment]
Because I need to demonstrate this website, I can only use the docker image version first, instead of the version I packaged myself.
You can try the attachment
[.evershop.zip](https://github.com/evershopcommerce/evershop/files/13838559/default.evershop.zip)

**Comment by treoden** [comment]
Hi @chendind ,

When you upgrade evershop to new version, you will have to re-build the component. Run "npm run build" again for the new build

Thanks
