### ISSUE TITLE
[FEATURE REQUEST] item description enhancement

### ISSUE THREAD

**Issue by TommasoCere** [evershopcommerce/evershop#439]
as we see on other e-commerce sites, it would be convenient to have the possibility of inserting, in addition to the quick description of the product that is already present, further detailed specifications.
To do this it would be convenient to be able to insert other details such as: images, tables, text or videos outside the main slider (e.g. amazon).
thanks

**Comment by jaymehta002** [comment]
assign me this issue

**Comment by treoden** [comment]
Hi @TommasoCere ,

EverShop provides rich text editor which help you to insert images, video to the product description. Not sure if that is what you are referring to?
