### ISSUE TITLE
[FEATURE REQUEST] SMTP Environment Variables

### ISSUE THREAD

**Issue by mariushosting** [evershopcommerce/evershop#442]
I'm unable to find the SMTP Environment Variables in the documentation.

**Comment by treoden** [comment]
Hi @mariushosting ,

EverShop does not support built-in SMTP server. For now we are using SendGrid for email services. Please check the extension below
https://evershop.io/extensions?tags=notification

Thanks

**Comment by mariushosting** [comment]
> Hi @mariushosting ,
> 
> EverShop does not support built-in SMTP server. For now we are using SendGrid for email services. Please check the extension below https://evershop.io/extensions?tags=notification
> 
> Thanks

Thanks, I hope in the future your awesome team can implement the easy Environment Variables for SMTP for docker compose to make it simply for a large number of users.
