### ISSUE TITLE
[BUG] Range slider component is not visible

### ISSUE THREAD

**Issue by 403-html** [evershopcommerce/evershop#445]
**Describe the bug**
Range slider component is not visible on demo page and how it works (so probably even after setuping it will show too)

**To Reproduce**
1. Go to for example https://demo.evershop.io/men
2. Look at the price range on the left
3. Bar is not visible

**Expected behavior**
Price range bar should be visible

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/57900160/ee11b3d6-98df-42db-8bbb-3b7131decace)

**Background (please complete the following information):**
 - OS: MacOS 14.2 (23C64)
 - Browser: Firefox 121.0.1 (64-bit)

**Comment by rahul-singh-takuli56** [comment]
Can i work on this issue?
