### ISSUE TITLE
[FEATURE REQUEST] Use url as product image instead of uploading

### ISSUE THREAD

**Issue by gmdig** [evershopcommerce/evershop#463]
My storage space is a bit small and I can’t upload a lot of images, so I need to use a third-party cloud storage service as a picture bed. The advantage of this is that you can save disk space and you can use the API to generate product pages in bulk more quickly

**Comment by treoden** [comment]
Hi @gmdig ,

If you are looking for the cloud storage extension for product image. Please checkout the extensions for AWS S3 and Azure here:
https://evershop.io/extensions

Thanks
