### ISSUE TITLE
i cant even continue the payment "cash on delivery"

### ISSUE THREAD

**Issue by ons33** [evershopcommerce/evershop#468]

**Comment by treoden** [comment]
Hi @ons33 ,

Can you share more details? What is the issue you are facing?

Thanks

**Comment by ons33** [comment]
hi again, it worked thank uu i ddnt know that i should add a methode before!
But i have a prb with modifying the welcome page text

**Comment by emmanuelh-dev** [comment]
I fixed this directly in the database. The issue was that nothing was being returned in the fetch. It's easy to fix, but there isn't a default set for this.
