### ISSUE TITLE
[BUG] dev mode is not working

### ISSUE THREAD

**Issue by mouaad-k** [evershopcommerce/evershop#473]
**Describe the bug**
by running `npm run dev` it runs all normally and if I visit localhost:3000 as showing in the terminal

**Expected behavior**
see my site 
**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/153355732/e3104b42-558a-4985-8a94-610d602b29e5)
**Background (please complete the following information):**
 - NodeJS 20.9.0
 - Postgres Version : the one given in the docker compose file
 - EverShop Version : latest
 - OS: windows
 - Browser: Chrome

**Additional context**
the build run flawlessly

**Comment by treoden** [comment]
Hi @mouaad-k 

Do you have any customization to the project? Can you share a screenshot with the browser console open, let's see if we have any error from the browser console log.

Thanks

**Comment by mouaad-k** [comment]
Hello @treoden 
**Thank-you for responding**

to give you more info about my setup 
I cloned this repo https://github.com/evershopcommerce/evershop
and run `npm i` and `npm run setup`
**I don't know if this is a correct way to run it ?**

when I said the build command run with out a problem, I've confused between projects `the cloned one` and the `one created with cli tool`

but when I used `npx create-evershop-app <name>` and follow the doc installation guide it works

**Comment by treoden** [comment]
Hi @mouaad-k ,

You should install the evershop from npm. You can use `npx create-evershop-app <name>` or manual way, You can check the docs here: https://evershop.io/docs/development/getting-started/installation-guide

Thanks
