### ISSUE TITLE
[BUG] cannot continue to Payment due to issue in Shipping Method

### ISSUE THREAD

**Issue by prashantrrai** [evershopcommerce/evershop#474]
**Describe the bug**
When adding address even though it is actual it is not working and not proceeding to payment page.

**To Reproduce**
1. Go to Cart Page
2. Click on Checkout
3. Fill up the Address Details and click continue to Payment
4. See error "Cannot Ship on this Address"

**Expected behavior**
It should work and proceed for payment gateway page.

**Screenshots**
<img width="931" alt="image" src="https://github.com/evershopcommerce/evershop/assets/86036396/622dc4e3-6569-453a-a2ec-b49a269c0ec6">

**Comment by treoden** [comment]
Hi @prashantrrai ,

You have to add some shipping method to the address first. You can do it form the admin panel
