### ISSUE TITLE
[BUG] Each variant is displayed as separate product

### ISSUE THREAD

**Issue by breathingcyborg** [evershopcommerce/evershop#488]
**Describe the bug**
Each variant is displayed as separate product in total there are num_variants + 1 products displayed.

**To Reproduce**
- Create a tshirt with following variants.
1. White, XXL
2. White, XL
3. White, SM
4. Black, SM
- Add them to category men
- Visit the men category page
- It will display 5 products. One product that we created originally. And one product for each variant created.
- Also in admin ui original product will show 4 variants. And each variant will show 3 variants.

**Expected behavior**
Only one product should be displayed.

**Screenshots**

Storefront category page
![storefront category page](https://github.com/evershopcommerce/evershop/assets/75165003/6c251570-7bf5-448a-a718-3b9ffc6f64af)

Admin products list page
![admin product list page](https://github.com/evershopcommerce/evershop/assets/75165003/8d885bb7-cfeb-46a0-b796-d31504723917)

Admin main product page (shows 4 variants)
![admin main product page](https://github.com/evershopcommerce/evershop/assets/75165003/ff9ec4a8-0460-4145-ad0a-b1d942136c14)

Admin variant product page (shows 3 variants)
![admin variant product page](https://github.com/evershopcommerce/evershop/assets/75165003/bd433c28-d82e-4ed0-ab67-2838f6de9b0d)

**Background**
 - NodeJS Version: 20.11.0
 - Postgres Version: postgres:16-alpine (docker)
 - EverShop Version: 1.0.0
 - OS: Ubuntu
 - Browser Firefox

**Comment by treoden** [comment]
Hi @breathingcyborg ,

In EverShop, Each variant is an actual product. 
However, you can use the visibility option to decide which variant to be show on the front Store. Ideally you have 1 variant with visibility on and turn off the rest.

Thanks

**Comment by breathingcyborg** [comment]
@treoden Thanks for the prompt reply. The solution you suggested works.
