### ISSUE TITLE
[BUG] Non existing variants can be selected in storefront

### ISSUE THREAD

**Issue by breathingcyborg** [evershopcommerce/evershop#489]
**Describe the bug**
Non existing variants can be selected in storefront

**To Reproduce**
* Create a tshirt with following variants.
1. White, XXL
2. White, XL
3. White, SM
4. Black, SM
* Notice that we dont have black, XL variant
* Go to product detail page
* Select Black, XL variant
* It lets you add black, XL variant and shows popup that says product added to cart.
* It does not actually add black, XL variant as it does not exist but adds black, SM variant.

**Expected behavior**
* It should not let you add non existing variants to cart.
* It should either disable the option or display error message
* Because when the success message appears, customers may mistakenly believe that they have successfully added that variant to the cart.

**Screenshots**
Success message is shown when you add non existing variant to cart.
![image](https://github.com/evershopcommerce/evershop/assets/75165003/a3323ca4-d75b-4ef9-b0f9-4310fbdf634f)

**Background (please complete the following information):**
- NodeJS Version: 20.11.0
- Postgres Version: postgres:16-alpine (docker)
- EverShop Version: 1.0.0
- OS: Ubuntu
- Browser Firefox

**Comment by treoden** [comment]
Hi @breathingcyborg ,

This issue is fixed in the new release (v1.1.0) Thanks
