### ISSUE TITLE
Task scheduler

### ISSUE THREAD

**Issue by IanYang112528** [evershopcommerce/evershop#499]
I want to use the task scheduling function, such as the plugin "node-cron". But I don't know how to use it in evershop, hope to get help, thank you!
node-cron : https://www.npmjs.com/package/node-cron

**Comment by treoden** [comment]
Hi @xiaofeimaoIan ,

EverShop offers event/subscribers. 
Can you share more about your use case?

Thanks

**Comment by xiaofeimaoIan** [comment]
Hi @treoden,
Thank you for your reply! My functional scenario is to check the qty number of products listed in the database every 2 hours, and if it is less than 5, it will alert me that the stock is low.
![image](https://github.com/evershopcommerce/evershop/assets/150426398/3ac526cd-dca4-4a24-b3c4-f1cafc08f84b)

Thanks

**Comment by treoden** [comment]
Hi @xiaofeimaoIan ,

For this scenario, you can leverage the event/subscriber. You create a subscriber subscriber to the "inventory_updated", you will have access to the old and new inventory data.
For more details of event/subscriber, check this docs: https://evershop.io/docs/development/knowledge-base/events-and-subscribers

Thanks

**Comment by xiaofeimaoIan** [comment]
OK, Thank you very much

**Comment by IanYang112528** [comment]
Hi @treoden,

My functional scenario is that some products in our store use products from third-party stores, so we need to check the QTY quantity of third-party stores every two days. If the number is less than 10, the product will be removed from the shelves！

Thanks

**Comment by treoden** [comment]
Hi @IanYang112528 ,

In this case, I think you have a integration somewhere for syncing products from your third-party to EverShop right? And you sync product information and inventory too?

**Comment by IanYang112528** [comment]
Hi @treoden,

Yes, we need to synchronize product information and inventory.
OK! Thank you for your reply!

**Comment by IanYang112528** [comment]
Hi @treoden,
Yes, we need to synchronize product information and inventory.
OK! Thank you for your reply!
