### ISSUE TITLE
[BUG] Can't rename or delete shipping methods

### ISSUE THREAD

**Issue by GPlay97** [evershopcommerce/evershop#503]
**Describe the bug**
It looks like its not possible to select a different name , once a shipping method has been stored. Even if selected a new method name on an existing one, it is not changing after safe.

**To Reproduce**
1. Create a shipping method
2. After saving, open the one and create a new name for it
3. Select the new name.
4. Save

**Comment by treoden** [comment]
Fixed in v1.1.0. Thanks
