### ISSUE TITLE
[BUG] Featured categories

### ISSUE THREAD

**Issue by GPlay97** [evershopcommerce/evershop#504]
**Describe the bug**
Not sure, how they are supposed to work, they seem to be hardcoded on the homepage. For featured products it looks like its working, since they seem to adapt, but categories don't change, even if deleted, or new ones created.

How to remove them or show the real categories?

**Comment by treoden** [comment]
Hi @GPlay97 ,

For those changes you will need to have a theme and then from your theme you can customize the components and show the desired content.

Thanks
