### ISSUE TITLE
[BUG] Custom copyright text not appearing

### ISSUE THREAD

**Issue by GPlay97** [evershopcommerce/evershop#505]
**Describe the bug**
As described in your docs, I changed copyright text via themeConfig in my config json. For other things , like currency, it is working, so the file is loaded. But copyright inside themeConfig seems to have no effect, since original default text still appears.

**Comment by treoden** [comment]
Can you share your config file here?

**Comment by GPlay97** [comment]
```Json
{
  "shop": {
    "currency": "EUR",
    "language": "de"
   },
  "themeConfig": {
    "copyright": "© 2024 Test. All rights reserved."
  }
}

```

**Comment by GPlay97** [comment]
![image](https://github.com/evershopcommerce/evershop/assets/29232849/196735ae-c3c1-4987-a690-d52f5f1f272d)

Easy fix. It needs to be `copyRight` instead of `copyright`. Wrong in documentation, took some time to come to the idea to have a look inside your code

**Comment by treoden** [comment]
Thanks @GPlay97 

Let me update the docs

**Comment by treoden** [comment]
Doc is updated. CLosing the ticket
