### ISSUE TITLE
[FEATURE REQUEST] - textbook or dropbox added to the product page.

### ISSUE THREAD

**Issue by qcardell** [evershopcommerce/evershop#509]
**Is your feature request related to a problem? Please describe.**
Feature - Add a textbook or dropbox so the customer could add notes or chose from options for an order.  We do custom orders so would like a way for the customer to pick from a choice of colors that we offer. With the textbox they could add the information manually or dropdown box they could choose from.

**Describe the solution you'd like**
Feature - Add a textbook or dropbox so the customer could add notes or chose from options for an order. We do custom orders so would like a way for the customer to pick from a choice of colors that we offer. With the textbox, they could add the information manually or dropdown box they could choose from.

**Describe alternatives you've considered**
Building out each color option as a variant.  Also looking for a way I could add this manually, like the option when adding the comment box.  Looking for an example of how to perform these actions.

**Additional context**
![image](https://github.com/evershopcommerce/evershop/assets/42754526/e42ab35e-8872-40a7-804b-7180472c4f75)
An example I found from another website that has the dropdown/text boxes option for an order.

**Comment by treoden** [comment]
Hi @qcardell ,

Did you have a change to play with the variant feature in EverShop?
Something like this 

![image](https://github.com/evershopcommerce/evershop/assets/6950941/84479370-30aa-4bfd-a4a4-346ea7a3c45e)

Thanks
