### ISSUE TITLE
[BUG] Order_placed event subscriber doesn't work

### ISSUE THREAD

**Issue by ogmaxbone** [evershopcommerce/evershop#514]

**Comment by ogmaxbone** [comment]
Trying to send order confirmation with resend but the event doesn't fire off

**Comment by ogmaxbone** [comment]
So the event will fire off if you change it to order_created

**Comment by treoden** [comment]
Yes the event name is `order_created`. Thanks

**Comment by Antoninnnn** [comment]
Hi i met the same problem, where should i change it? Should i chenge the event name from order_placed to order_created?
