### ISSUE TITLE
[BUG] hello how to use rest api in localhost 

### ISSUE THREAD

**Issue by abdurahmon97v** [evershopcommerce/evershop#515]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Background (please complete the following information):**
 - NodeJS Version
 - Postgres Version
 - EverShop Version
 - OS: [e.g. Window, Ubuntu, Mac-OS]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by treoden** [comment]
You can use tool like postman and follow the docs here: https://evershop.io/docs/api/overview
