### ISSUE TITLE
[BUG] Paypal redirecting to localhost on prod enviroment

### ISSUE THREAD

**Issue by cheskoxd** [evershopcommerce/evershop#529]
**Describe the bug**
After completing the payment on Paypal, I should get redirected to the main site, but I'm getting redirected to localhost:3000

**To Reproduce**
1. Go to Pay an order
2. Click on Paypal
3. Pay with paypal
4. Redirects to localhost instead of main site

**Expected behavior**
Should redirect to the success order page, like with stripe, after you pay it shows a message that the order was placed

**Background (please complete the following information):**
 - NodeJS Version
 - Postgres Version
 - EverShop Version Latest
 - OS: Windows 
 - Browser Chrome, Safari, Edge

**Additional context**

**Comment by treoden** [comment]
Hi @cheskoxd ,

You need to configure your home url from your config file (`config/default.json`)
Something like this

```
{
    "shop": {
        "homeUrl": "https://www.example.com",
        "weightUnit": "pound"
    }
}
```

**Comment by cheskoxd** [comment]
Yea, I have it exactly like that:
![image](https://github.com/evershopcommerce/evershop/assets/71806950/bded04d0-1196-40f8-952a-75354a16dcfa)

but when I try to process a payment, it redirects me to localhost

**Comment by treoden** [comment]
Hi @cheskoxd ,

Are you talking about the payment successful redirection? Can you share some screenshot of the redirection page and your config folder?

Thanks

**Comment by cheskoxd** [comment]
Update, it's working now, I just redeployed and tried again with a test account and it worked last time I got the error was with a live account, but I guess well see how it goes, thanks a lot @treoden ❤️
