### ISSUE TITLE
[BUG]Error: 404: NOT_FOUND, after Deploying on Vercel

### ISSUE THREAD

**Issue by metinlleshi** [evershopcommerce/evershop#533]
**Describe the bug**
Deploy project to Vercel through Github

**To Reproduce**
1.Connect Git Repository
2.Add .Env variables (database variables)
3.Deploy on Vercel

**Expected behavior**
Page should open like in Heroku

**Additional context**
Instead the deployment process is successful but after clicking the generated URL, is gives the Error: 404:Not Found.

I am guessing it has something to do with Output Directory.

Which file should we add as Output Directory?

**Comment by treoden** [comment]
Vercel is for static website. I suggest you go with Azure/Aws ..etc
