### ISSUE TITLE
[BUG] Category and subcategory

### ISSUE THREAD

**Issue by leandrosantoss** [evershopcommerce/evershop#536]
**Describe the bug**
No cadastro de categoria tenho subcategorias:

1. Tabacaria
     1.2. Essencias
             1.2.1. Pimp
![image](https://github.com/evershopcommerce/evershop/assets/59751373/d1159d85-a9e2-4a64-ad73-3d2e7e7e8383)

When accessing Tabacaria
![image](https://github.com/evershopcommerce/evershop/assets/59751373/107c6b16-5d7a-45c8-aa40-ee89933d2094)

![image](https://github.com/evershopcommerce/evershop/assets/59751373/fe4e7feb-436f-4f6c-9d0b-609217ba59f0)

It belongs to the Essences category and the Pimp Subcategory
![image](https://github.com/evershopcommerce/evershop/assets/59751373/5c107cc4-019e-4a7a-a922-d94380d27935)

When clicking on a parent category shouldn't it filter products from its children?
Shouldn't this filter be a parent and child tree?

Here a recursion problem:
![image](https://github.com/evershopcommerce/evershop/assets/59751373/a36b6a15-64a5-4a28-a68d-dd4f3d72e948)

Evershop: 1.1.0

**Comment by leandrosantoss** [comment]
Hi, @treoden 

In registering categories we have this problem. There is no scroll and I can't see the entire tree.

![image](https://github.com/evershopcommerce/evershop/assets/59751373/6c14e4cf-7bff-4f31-ba7b-477b1bdb9cef)

Was it resolved in your commit too?

**Comment by treoden** [comment]
Fixed. Closing the issue
