### ISSUE TITLE
[BUG] Shipping Method Popup not scrollable

### ISSUE THREAD

**Issue by sk-netc** [evershopcommerce/evershop#540]
**Describe the bug**
I was trying to add Shipping zone and shipping method but the screen is not scrollable enough for me to add all options

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Shipping Setting > Create new shipping zone'
3. Scroll down to 'Add Method'

**Expected behavior**
I should be able to add all the parameters to define shipping price, but popup is not scrollable to add enough parameters.

**Screenshots**
![image](https://github.com/evershopcommerce/evershop/assets/146923969/f09ce552-0515-45b0-a0d8-10c6f632366b)

**Background (please complete the following information):**
 - NodeJS Version - v20.10.0
 - Postgres Version - 16.3
 - EverShop Version - 1.1.0
 - OS: [e.g. Window, Ubuntu, Mac-OS] - Windows 11
 - Browser [e.g. Chrome, Safari] - Chrome

**Additional context**

**Comment by flashpunch0-0** [comment]
Hi please close this issue if fixed

**Comment by treoden** [comment]
Fixed. Closing the issue
