### ISSUE TITLE
[FEATURE REQUEST] Is there a way to order the categories in the nav menu?

### ISSUE THREAD

**Issue by Chief-T1** [evershopcommerce/evershop#544]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to sort the order categories are displayed in when shown in the navigation menu. 

**Describe the solution you'd like**
I would like to be able to control the category position in the menu via the user interface. 

**Describe alternatives you've considered**

**Additional context**

**Comment by treoden** [comment]
From v1.2, you can use the menu widget and be able to sort the order categories.

Thanks
