### ISSUE TITLE
Change the icountry does'nt reflect the currency

### ISSUE THREAD

**Issue by shubu998** [evershopcommerce/evershop#554]
Change the icountry does'nt reflect the currency

**Comment by treoden** [comment]
Hi @shubu998 ,

Sorry, icountry and currency?  Please explain more about what you did and what is the expectation

**Comment by jeswanisumit1999** [comment]
Not every country has $ as currency symbol. So we admin should have option to change this. Or it should automatically set when we set country.

**Comment by flashpunch0-0** [comment]
the AreaProps :{row} which is being passed to PriceRow component  itselfcontains $ as sign 
According to what I have understood there can be two ways to do it 
1 - set the global variable when you set the store information in the settings.
2- When a new Product is added just pass the new current country sign with it and a global variable will not be required.

**Comment by treoden** [comment]
Hi @jeswanisumit1999 , @flashpunch0-0 

Did you change the configuration here: https://evershop.io/docs/development/knowledge-base/configuration-guide#shop-configuration

Thanks

**Comment by flashpunch0-0** [comment]
Hi @treoden  
tried to sort of do what you said but not able to see any particular changes 
I think we should set the storeCurrency when the store settings is changed (a country is chosen) .
![image](https://github.com/evershopcommerce/evershop/assets/21008005/9c7f8510-dfb7-450b-8a1b-c76337a2a745)

This will definitely help us as in the new product form   we have 
![image](https://github.com/evershopcommerce/evershop/assets/21008005/1ce4df60-19e8-416a-9e2c-4c171b02f690)

in the query also we are passing this storeCurrency 
so, if somehow you can change this storecurrency when you change the store setting then it will be a lot easier, I think.

**Comment by treoden** [comment]
Hi @flashpunch0-0 

You change it from the configuration file. Please read this docs: https://evershop.io/docs/development/knowledge-base/configuration-guide
