### ISSUE TITLE
[BUG] Error after upgrading to 1.1.0

### ISSUE THREAD

**Issue by ogmaxbone** [evershopcommerce/evershop#559]
So after i updated evershop via npm install @evershop/evershop@1.1.0
it gave me this error. Even if i downgrade to 1.0.0 it gives me same error but if i disable azure then it works again on the old version. Before azure used to work on the old version as well.
**To Reproduce**
1. NPM run build
2. npm run start

![Screenshot 2024-06-05 at 9 02 39 AM](https://github.com/evershopcommerce/evershop/assets/65430229/248a17bc-e70d-4bf5-bf4f-51bd5fe4cc5b)

**Comment by ogmaxbone** [comment]
also it says evershop@0.1.0 so idk if i upgraded correctly

**Comment by ogmaxbone** [comment]
after i downgraded to 1.0.0 azure is working again and no error. however i want to upgrade to 1.1.0 to fix the blank checkout screen

**Comment by treoden** [comment]
Hi @ogmaxbone ,

Are you using the evetheme? if yes please upgrade your theme. You can download the latest version from GitHub:

https://github.com/evershopcommerce/evetheme/

**Comment by ogmaxbone** [comment]
<img width="953" alt="Screenshot 2024-06-09 at 7 24 47 PM" src="https://github.com/evershopcommerce/evershop/assets/65430229/c2d7d185-dbfc-476b-a500-8c016d881d72">



I upgraded the theme and still this error, however the site runs now

**Comment by ogmaxbone** [comment]
@treoden

**Comment by treoden** [comment]
Hi @ogmaxbone ,

Are you using the Azure file storage extension? Please upgrade that extension too

**Comment by ogmaxbone** [comment]
Updated all the extensions

**Comment by ogmaxbone** [comment]
fixed it it was the error variable in my extension
