### ISSUE TITLE
[BUG] Payment Method is required

### ISSUE THREAD

**Issue by leandrosantoss** [evershopcommerce/evershop#570]
**Describe the bug**
I created a new payment method "sendiopay", but in the POST /orders it is showing the error:
{"error":{"message":"Payment method is required","status":400}}

**Expected behavior**
Same behavior as Payment Cash on Delivery

**Screenshots**

Code:
![image](https://github.com/evershopcommerce/evershop/assets/59751373/eeded942-ddbe-47d0-9ca9-67c9aed7b1a5)

Admin
![image](https://github.com/evershopcommerce/evershop/assets/59751373/df2c349d-5916-49ad-ae6a-94548ce60a89)

Store
![image](https://github.com/evershopcommerce/evershop/assets/59751373/687ff38d-6ea1-45c0-a5f0-b8b1ecdf906b)

![image](https://github.com/evershopcommerce/evershop/assets/59751373/a4308649-7a2e-4c9e-b77e-085c789219ee)

**Background (please complete the following information):**
 - NodeJS 20
 - EverShop 1.1.0

Can you help me because this error is showing? I don't understand what's missing.

**Comment by treoden** [comment]
Hi @leandrosantoss ,

You need to take an extra step: Create a payment method validator.

You can do it by adding your validator to the cart processor. Below is an example:

```
// <your extension>/bootstrap.js
const { addProcessor } = require('@evershop/evershop/src/lib/util/registry');
const { getSetting } = require('@evershop/evershop/src/modules/setting/services/setting');

module.exports = () => {
  addProcessor('cartFields', (fields) => {
    fields.push({
      key: 'payment_method',
      resolvers: [
        async function resolver(paymentMethod) {
          if (paymentMethod !== 'sendiopay') {
            return paymentMethod;
          } else {
            // Validate the payment method
            const sendiopayStatus = await getSetting('sendiopayStatus '); // Your status setting, change it to your actual field name
            if (parseInt(sendiopayStatus, 10) !== 1) {
              return null;
            } else {
              this.setError('payment_method', undefined);
              return paymentMethod;
            }
          }
        }
      ]
    });
    return fields;
  });
};
```

Thanks

**Comment by leandrosantoss** [comment]
Hi @treoden 

I did it here, but it didn't work. Anything I missed?

![image](https://github.com/evershopcommerce/evershop/assets/59751373/38470b3e-c0af-462d-99be-d1a7570b816e)

![image](https://github.com/evershopcommerce/evershop/assets/59751373/f139a065-3856-46e5-a13c-e3dbb2246e78)

**Comment by treoden** [comment]
Hi @leandrosantoss ,

Everything look fine. Not sure why the line #18 does not output anything.
Can you put more console to the `addProcessor` callback function and check the output? Like before the line 8 and 12?

Thanks

**Comment by leandrosantoss** [comment]
Hi @treoden 

I put a breakpoint inside addProcessor and I could see that stripe, paypal, etc. are being logged. But mine is not. Is there any configuration missing?

![image](https://github.com/evershopcommerce/evershop/assets/59751373/c53ef356-4917-4b0a-9c65-ab940cf456c3)


The console log did not work

**Comment by leandrosantoss** [comment]
@treoden 

I found the problem... bootstrap.js was outside of my extension folder

![image](https://github.com/evershopcommerce/evershop/assets/59751373/192d206b-2b60-4562-a8cd-a892e2bf663d)

I'll test it now

Thanks

**Comment by leandrosantoss** [comment]
It worked!

Thanks for your help

![image](https://github.com/evershopcommerce/evershop/assets/59751373/16960a81-0976-4950-a5f2-e186cd838d27)
