### ISSUE TITLE
[BUG] Category scrolling on Mobile

### ISSUE THREAD

**Issue by leandrosantoss** [evershopcommerce/evershop#574]
**Describe the bug**
Go to the product page and try scrolling through the categories

**Expected behavior**
Able to scroll and view all categories

**Screenshots**

https://github.com/evershopcommerce/evershop/assets/59751373/52ef8973-1a7d-4c24-9ec0-0d2199790d40

**Background (please complete the following information):**
 - NodeJS 20
 - EverShop 1.1.0

**Comment by adexh** [comment]
Opened pull request #578 for this issue.
