### ISSUE TITLE
[SUPPORT] customise store attributes

### ISSUE THREAD

**Issue by cody151** [evershopcommerce/evershop#591]
I haven't been able to figure out how to put my own logo as currently it just shows "evershop" , I'd like to customise my store with my own logo and text etc. i used ```npx create-evershop-app``` to create and then build it. Any ideas?

**Comment by treoden** [comment]
Hi @cody151 
If you want to change the logo. check this: https://evershop.io/docs/development/knowledge-base/configuration-guide#theming-configuration
Thanks

**Comment by cody151** [comment]
> Hi @cody151 If you want to change the logo. check this: https://evershop.io/docs/development/knowledge-base/configuration-guide#theming-configuration Thanks

Thanks so much, but I'm not sure which file I am supposed to put this in 
```Theming configuration
Theming configuration contains the configuration for the theme. You can configure the logo, favicon, and the meta tag for the storefront.

{
    "themeConfig": {
        "logo": {
            "alt": "You amazing shop logo",
            "src": "/logo.png",
            "width": 100,
            "height": 100
        },
        "headTags": {
            "links": [],
            "metas": [],
            "scripts": []
        },
        "copyRight": "© 2022 Evershop. All Rights Reserved."
    }
}``` 

Is it meant to go into package.json?

**Comment by treoden** [comment]
Please read the document, it is from the top of the page: https://evershop.io/docs/development/knowledge-base/configuration-guide#configuration-file-location

Thanks

**Comment by cody151** [comment]
> Please read the document, it is from the top of the page: https://evershop.io/docs/development/knowledge-base/configuration-guide#configuration-file-location
> 
> Thanks

Solved, thanks very much!
