### ISSUE TITLE
How to change the validity period of sid

### ISSUE THREAD

**Issue by IanYang112528** [evershopcommerce/evershop#593]
Hi @treoden 

I want to extend the validity period of my sid, how can I set it?
![sid](https://github.com/user-attachments/assets/b8174903-87a6-4b36-a420-b2d97daa512f)

Thanks

**Comment by treoden** [comment]
Hi @IanYang112528 ,

You can now change the cookie lifetime by this configuration

```
{
	"system": {
		"session": {
			maxAge: <milisecond>
		}
	}
}
```

Thanks
