### ISSUE TITLE
[FEATURE REQUEST] Display stock in the product page

### ISSUE THREAD

**Issue by Billos** [evershopcommerce/evershop#597]
**Is your feature request related to a problem? Please describe.**
I'd like to see how many items I can order instead of just trying multiple times if the amount I want can be ordered

**Describe the solution you'd like**
A simple line next to the SKU to show the stock

**Additional context**
An option to show or to hide this information

**Comment by treoden** [comment]
Hi @Billos ,

We do not recommend to show the real stock on the frontend. Sometime you don't really want to tell customer how many of item are available in your stock.

I suggest you only display stock in case it is low.

Thanks
