### ISSUE TITLE
[BUG] New Editor Overlap

### ISSUE THREAD

**Issue by mpenfold1987** [evershopcommerce/evershop#617]
When creating custom pages the editor has an overlap on selecting inser etc.

1. Go to 'CMS Pages (any custom page'
2. Click on '+ or burger'
5. See error

![Screenshot 2024-09-04 082625](https://github.com/user-attachments/assets/c67b4ac3-1708-4794-bfac-918dbf0ef49f)
![Screenshot 2024-09-04 082630](https://github.com/user-attachments/assets/7d195189-9363-4fdb-8716-4e79d3feb536)

**Comment by mpenfold1987** [comment]
this isnt just CMS pages it seems constant across all editor instances

**Comment by mpenfold1987** [comment]
your fix in the Commit worked but its still acting funny with items outside of current selection

![Screenshot 2024-09-09 122534](https://github.com/user-attachments/assets/b1e72416-d07f-4e0d-b54e-a58eb68d68b0)
![Screenshot 2024-09-09 122640](https://github.com/user-attachments/assets/bdf6669a-4b62-48f2-840b-b1a622b51dc9)

**Comment by treoden** [comment]
Fixed in v1.2.1. Thanks
