### ISSUE TITLE
[BUG] frontend broken image on latest version 

### ISSUE THREAD

**Issue by aziz191546** [evershopcommerce/evershop#618]
I encountered a bug when creating a new product from the admin page. After adding an image, it displays correctly in the admin panel, but it doesn't show on the frontend. Instead, it only shows a broken image icon.

I tested this with a fresh install of the latest version of Evershop and a new database, so I believe this is a bug in the current version.

Please see the attached screenshot for more details.

Steps to Reproduce:

Go to the admin panel.
Create a new product and add an image.
Check the frontend product page.
Expected result: The product image should display properly on the frontend. Actual result: A broken image icon appears instead of the product image.
![Screenshot 2024-09-05 220456](https://github.com/user-attachments/assets/21cebee0-b5ac-4d69-8628-d3c9e4de540b)

**Comment by GabrielGavrilov** [comment]
I was unable to replicate the bug on my end with the latest version.

**Comment by dana-Navee** [comment]
Having the same issue with the latest version

**Comment by aziz191546** [comment]
This happens when you upgrade to a new version To solve this issue, you need to create a new database and not use the old database.
