### ISSUE TITLE
No configurations found in configuration directory(it exists)

### ISSUE THREAD

**Issue by Shreyansh99** [evershopcommerce/evershop#619]
**Describe the bug**
after adding config directory, getting a warning that says No configurations found in configuration directory
**To Reproduce**
after setting up evershop and created database when we run npm run build command it showing a warning that No configurations found in configuration directory but it is there.

**Expected behavior**
If configuration directory exists no warning should be there. If configuration directory does not exists it should show warning there only.

**Screenshots**
![Screenshot (6)](https://github.com/user-attachments/assets/fb72e684-2c8a-4f51-9995-c2e99bd7f07a)
![Screenshot (7)](https://github.com/user-attachments/assets/5d9e8356-f482-4adb-869f-d1891d198f21)

**Background (please complete the following information):**
 - NodeJS Version -  20.5.1
 - Postgres Version - 15
 - EverShop Version - 1.2.0
 - OS: Ubuntu 24.04

**Comment by mpenfold1987** [comment]
have you got the config files setup as these are manual not auto added? 

![image](https://github.com/user-attachments/assets/7d583135-8919-4f04-9140-f2bc0fe5ca01)

**Comment by Shreyansh99** [comment]
i have added to config file by myself those are being added manually

**Comment by treoden** [comment]
Hi @Shreyansh99 ,

The `config` folder will be empty after a fresh installation (default configuration will be applied). You can create your own configuration file when you want to change the default setting. Thanks
