### ISSUE TITLE
[BUG] Add item to cart with SKU (Web and API)

### ISSUE THREAD

**Issue by leandrosantoss** [evershopcommerce/evershop#628]
**Describe the bug**
In version 1.1.0 I added a product to the cart, but another one was added.

**Screenshots**
![image](https://github.com/user-attachments/assets/981128ab-18b9-4477-b7b0-0cf637bcff27)
SKU: 0910

![image](https://github.com/user-attachments/assets/4b617d94-c7ea-40c3-9285-01132580d2f1)
Other SKU was added

![image](https://github.com/user-attachments/assets/8161c57a-c58f-42e3-a4f7-05a6922366f6)
I believe this is the problem. We use numeric sku, which can match a PK (product_id) and pull another product

In the addItem or addCartItem API I will use uuid and it should solve the problem, but on the web the problem will continue.

**Background (please complete the following information):**
 - NodeJS Version - 20
 - EverShop Version - 1.1.0

**Comment by treoden** [comment]
Hi @leandrosantoss ,

I am sorry about this. In the 1.2.0, the `createItem` method only accept product ID. So if you are using SKU, you will need to resolve it to the `productID` and pass to the `createItem` method

Thanks
