### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by AdarshMishra9611** [evershopcommerce/evershop#631]
Option to Change Webpage Title from Admin Page

**Is your feature request related to a problem? Please describe.**
Its really time-consuming and  frustrating...... when I cannot easily change the website's title without modifying code. It would be useful to have a setting in the admin panel to update the website title dynamically, improving usability for non-developers who manage content via the admin interface

**Describe the solution you'd like**

**Describe alternatives you've considered**
I would like an option in the admin panel that allows users, including non-developers, to update the webpage title directly. This feature should automatically update the <title> tag of the site, saving time and avoiding the need for manual code changes. Ideally, this would be a simple input field within the settings or configuration section of the admin dashboard.

**Additional context**
This feature would greatly benefit non-technical users who manage site content through the admin panel. Currently, changing the title requires access to the code, which is not ideal for users without a development background. By allowing title customization in the admin settings, it would reduce the need for development time and enhance user-friendliness.

**Comment by treoden** [comment]
Hi @AdarshMishra9611 

If you are talking about the meta title of the homepage, you can change it from admin panel 
![image](https://github.com/user-attachments/assets/4fa15d36-fb43-4e82-9913-707867f8dfe3)

Other sub pages like product, category will be using the name of the item (product, category) as the title

Thanks
