### ISSUE TITLE
[FEATURE REQUEST] Option to Add Logo and Favicon from Admin Panel

### ISSUE THREAD

**Issue by AdarshMishra9611** [evershopcommerce/evershop#632]
**Is your feature request related to a problem? Please describe.**
Currently, adding a logo and favicon requires modifying the code manually. This can be time-consuming for non-developers who manage the site through the admin panel.

**Describe the solution you'd like**
An option in the admin panel where users can upload and set a custom logo and favicon for the website, simplifying the branding process without requiring code changes.

**Additional context**
This would make it easier for non-technical users to brand their store more efficiently.

**Comment by treoden** [comment]
You don't need to modify the core files. Please read the docs here: https://evershop.io/docs/development/knowledge-base/configuration-guide#logo
