### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by andres1138** [evershopcommerce/evershop#637]
**Is your feature request related to a problem? Please describe.**
How do I change the title of the shop? I tried “title” within headstands on the config file with no luck

**Describe the solution you'd like**
A Config option if there isn’t one already. 

 Thank you for all your hard work with evershop, it’s exactly what I was looking for. I got everything set for my shop, I just can’t figure out how to change the title, I have a custom favicon but the default title is still there.

**Comment by andres1138** [comment]
I am an idiot, all I had to do was create a custom js file. Thank you anyway.

**Comment by andres1138** [comment]
@vitran96 I believe at the time. I had overly complicated it. What I did was write a small script to forcefully change the title of the web site that was saved in a separate js file. This is what my config file looked like at the time.

```js
{
    "shop": {
        "currency": "USD",
        "language": "en",
        "weightUnit": "ct"
    },

    "system": {

        "theme": "dgh"
    },

"themeConfig": {
        "headTags": {
                "scripts": [
                    {

                        "type": "text/javascript",
                        "src": "/titlescript.js",
                        "async": false
                    }
                ],

            "links": [
                {
                    "type": "image/svg+xml",
                    "rel": "icon",
                    "href": "/favicon.svg"
                }
            ]
        }
    }
}
```

The reason I am saying I over thought this and complicated it is because in the admin dashboard under Settings. You can change the title of the website, all this I did was completely unnecessary. I hope this helps.

**Comment by vitran96** [comment]
As for the title, admin's settings support changing the homepage title name.
