### ISSUE TITLE
[FEATURE REQUEST] Change what product variant to display in widgets

### ISSUE THREAD

**Issue by Belvin-04** [evershopcommerce/evershop#640]
**Is your feature request related to a problem? Please describe.**
I have added a product with some variants, I need an option from where I can select which product variant to be displayed whenever I create a widget

**Describe the solution you'd like**
A solution where we can either select what should be displayed on the homepage or delete a product and choose one of the variant as the main product would also work

**Comment by treoden** [comment]
You can just create a collection with your desired products and then use the "Collection products" widget. 

Thanks
