### ISSUE TITLE
No configurations found in config directory(it exists)

### ISSUE THREAD

**Issue by Shreyansh99** [evershopcommerce/evershop#644]
Describe the bug
after adding config directory, getting a warning that says No configurations found in configuration directory
To Reproduce
after setting up evershop and created database when we run npm run build command it showing a warning that No configurations found in configuration directory but it is there.

Expected behavior
If configuration directory exists no warning should be there. If configuration directory does not exists it should show warning there only.

Screenshots
![Screenshot (6)](https://github.com/user-attachments/assets/b0501e4d-9e5a-44a8-9dcd-edb82bd39405)
![Screenshot (7)](https://github.com/user-attachments/assets/6a5b840f-a9e5-47e5-b089-29461daad493)
![Screenshot (9)](https://github.com/user-attachments/assets/7b0e892f-23d3-4027-8b62-50e2c421b16c)

Background (please complete the following information):

NodeJS Version - 20.5.1
Postgres Version - 15
EverShop Version - 1.2.0
OS: Ubuntu 24.04

**Comment by treoden** [comment]
Hi @Shreyansh99 ,

After a fresh installation, no configuration file will be generated (EverShop manages it from the core). You only need a configuration file when you want to update/change the default configuration.
