### ISSUE TITLE
[BUG] Payment method is required

### ISSUE THREAD

**Issue by dheeth** [evershopcommerce/evershop#656]
**Describe the bug**
I am trying to use this extension - https://github.com/dheeth/evershop-razorpay and when I click Checkout I get Payment method is required on Order API. It seems related to #570 but I can see that bootstrap.js is in proper place

**To Reproduce**
1. Go to Cart
2. Try to checkout with some products
3. It gets stuck in loading on checkout button and there is error in network API call on - `/api/orders`
Error is
```
{error: {message: "Payment method is required", status: 400}}
```

**Screenshots**
<img width="1440" alt="Screenshot 2024-10-30 at 12 16 50 PM" src="https://github.com/user-attachments/assets/c98bc189-f789-46b2-9f21-72ca3c845f4a">

**Background (please complete the following information):**
 - NodeJS Version - v20.17.0
 - Postgres Version - 14.13
 - EverShop Version - latest
 - OS: Ubuntu
 - Browser: Brave

**Comment by treoden** [comment]
Hi @dheeth 

The extension you are using was not developed by EverShop core team and not a part of this repo, So I suggest you either check/report issue on the provider repo.

Thanks
