### ISSUE TITLE
[BUG] When deploying to AWS ec2 instance  Reached heap limit Allocation failed

### ISSUE THREAD

**Issue by juancarlosv2711** [evershopcommerce/evershop#661]
**Describe the bug**
When deplying to AWS ec2 instance using the bash script from [this documentation ](https://evershop.io/docs/development/deployment/deploy-evershop-to-aws) 
I get the following error
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/803e8331-2552-4182-89b7-b723d3b26c50">

I have already tried
- I have tried downgrading to node js 14
- Increase memory allocation
- increase ec2 instance specs
- swap memory allocation

None of them have worked

**Background (please complete the following information):**
 - NodeJS Version v20.17.0
 - Postgres Version 16.3
 - OS: Mac-OS

**Additional context**

**Comment by dheeth** [comment]
What's the instance type you are using? and which instance type have you already tried?

**Comment by Chriswva** [comment]
awdgaw

**Comment by juancarlosv2711** [comment]
> What's the instance type you are using? and which instance type have you already tried?

I am using ec2 Ubuntu instance t2.micro, I tried also with t2.small but It didn't work

**Comment by treoden** [comment]
Can you try adding `--skip-minify` to the build command? 
`npm run build -- --skip-minify`

**Comment by dheeth** [comment]
I am running it on m6a.xlarge instance and it's working fine for me even without --skip-minify

**Comment by juancarlosv2711** [comment]
> I am running it on m6a.xlarge instance and it's working fine for me even without --skip-minify

This worked, thank you!!

**Comment by dhileep47** [comment]
While attempting to build Evershop on an Ubuntu EC2 instance using the latest `dev` branch, the build process consistently gets stuck at:

- Client: sealing (92%)
- Server: building (59%)

I tried increasing the Node.js heap limit to 16GB using (OS: Ubuntu 22.04 (EC2 t2.medium + 16GB swap)):
NODE_OPTIONS="--max-old-space-size=16384" npm run build -- --skip-minify

Could you please advise on how to resolve this hang or suggest any additional configurations needed for a successful build?


![Image](https://github.com/user-attachments/assets/45ad880f-ca0f-4afe-ac50-94f6f7044806)
