### ISSUE TITLE
[BUG] Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Alert`, expected a single ReactElement

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#91]
**Describe the bug**
Invalid prop provided to the Alert component.

**To Reproduce**
1. Start project in development mode
2. Visit home page
3. See the warning message in the developer console

**Expected behavior**
The warning message should disappear
**Screenshots**
![Screenshot from 2022-08-21 21-15-24](https://user-images.githubusercontent.com/6950941/185795384-2f0544f0-1bdb-4923-be7c-20350468be33.png)

**Comment by timagixe** [comment]
Hello @treoden, please assign this issue on me, I will fix it while working on https://github.com/evershopcommerce/evershop/issues/93. Cheers!

**Comment by timagixe** [comment]
@treoden I while working on this issue, I have found out that there are few other potentials places that are likely to introduce the same error `Invalid prop`.

<img width="333" alt="Screen Shot 2022-08-23 at 12 17 50 AM" src="https://user-images.githubusercontent.com/60817786/186020977-aae27c56-b5fb-4cf3-9435-ac553b079ec2.png">

Should I adjust those children's PropTypes from `element` to `node` within the scope of #95? What do you think?

**Comment by treoden** [comment]
Hi @timagixe,

Let's create another issue for them. I will do it soon
Thanks

**Comment by timagixe** [comment]
@treoden, here it is - https://github.com/evershopcommerce/evershop/issues/97
