### ISSUE TITLE
[BUG] Use `PropTypes.node` for children prop instead of `PropTypes.element`

### ISSUE THREAD

**Issue by timagixe** [evershopcommerce/evershop#97]
**Describe the bug**
In order to avoid errors like `Invalid prop children of type array supplied to Component, expected a single ReactElement` we should replace `PropTypes.element` where is used with `PropTypes.node`. According to the [documentation](https://reactjs.org/docs/typechecking-with-proptypes.html#:~:text=//%20Anything%20that%20can%20be%20rendered%3A%20numbers%2C%20strings%2C%20elements%20or%20an%20array%0A%20%20//%20(or%20fragment)%20containing%20these%20types.%0A%20%20optionalNode%3A%20PropTypes.node%2C) `Element` is a subtype of `node` which includes numbers, strings, elements or an array (or fragment) containing these types.

**To Reproduce**
1. Start project in development mode
2. Visit home page
3. See the warning message in the developer console

**Expected behavior**
No errors observed in console.

**Screenshots**
![185795384-2f0544f0-1bdb-4923-be7c-20350468be33](https://user-images.githubusercontent.com/60817786/186084278-6fb9af8f-20f4-43bf-af27-09ae39b36366.png)

**Background (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by abwhb** [comment]
Hey @treoden, 
If this issue is not assigned to anyone, I can work on it.

**Comment by evershopcommerce** [comment]
Hey @abwhb ,the  ticket is asigned to you. Thanks

**Comment by treoden** [comment]
Thanks @abwhb and @timagixe
